### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [greg7mdp/sparsepp#1]
I would like to point out that identifiers like "[`__sparsepp__h_`](https://github.com/greg7mdp/sparsepp/blob/a40039066dfba2e9df490f2ddd06e3376d25a67f/sparsepp.h#L1)" and "[`__spp_utils__h_`](https://github.com/greg7mdp/sparsepp/blob/a40039066dfba2e9df490f2ddd06e3376d25a67f/spp_utils.h#L72)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by greg7mdp** [comment]
I was not aware of an existing C++ naming convention for these guard identifiers. Can you point me to a source describing this convention? I'd be happy to follow it.

**Comment by elfring** [comment]
Would you like to [take another look at corresponding information sources](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by greg7mdp** [comment]
Thank you for the link and for filing the issue, Markus, issue is fixed.

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/greg7mdp/sparsepp/commit/bd745f6af5fda622959f14fd12a375496e42f364 "Deletion of a few underscores")
