### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by dbseraf** [greg7mdp/sparsepp#10]
Just FYI:

1. on Cygwin on Windows using g++ version 5.4, I had to change  the option '-std=c++0x' to '-std=gnu++ 0x' because it complained strdup was undefined.  

2. compile failed on SuSE/SLES 12 and openSuSE Leap 42.1 on ARM64 with g++ version 4.8.5 because cpuid.h doesn't exist.  I suspect this is an ARM64-specific problem, but I don't have an x86 SuSE system to check against.

**Comment by greg7mdp** [comment]
Hi,

Thank you very much for the report. I would like for sparsepp to build everywhere, but it is tough to test on many platforms, so reports like yours help a lot.

I just checked in a change that should address your second issue, provided that the absence of cpuid.h was the only problem.

I don't know what to do for the first issue. I don't use strdup internally, so I'm not sure where the error came from, or why the option change resolved the issue. Do you have a suggestion for a change in sparsepp.h that would allow the compilation with '-std=c++0x'?

Thanks,

greg

**Comment by Bu11etmagnet** [comment]
@dbseraf 
Where did it complain about strdup? An error message would be nice.

**Comment by dbseraf** [comment]
My apologies.  That was a poor bug report.

On cygwin:

$ make
g++ -O2 -std=c++0x -D_CRT_SECURE_NO_WARNINGS spp_test.cc -o spp_test
spp_test.cc: In member function 'void {anonymous}::ValueType::set_s(const char*)':
spp_test.cc:986:79: error: 'strdup' was not declared in this scope
         s_ = (new_s == NULL ? kDefault : reinterpret_cast<char*>(_strdup(new_s)));
                                                                               ^
spp_test.cc: In function 'ItemType {anonymous}::UniqueObjectHelper(int) [with ItemType = char*]':
spp_test.cc:1204:66: error: 'strdup' was not declared in this scope
         g_unique_charstar_objects[(size_t)index] = _strdup(buffer);

On SuSE/openSuSE, the new code compiles  and runs successfully.   Thanks.

**Comment by Bu11etmagnet** [comment]
You need -D_XOPEN_SOURCE=700 or some _POSIX_C_SOURCE value for strdup to be visible on Cygwin

**Comment by Bu11etmagnet** [comment]
Fix in #11

**Comment by greg7mdp** [comment]
@Bu11etmagnet, thanks a lot for the fixes. For some reason I didn't have this issue on my cygwin install with an older g++ version.
