### ISSUE TITLE
Assertion

### ISSUE THREAD

**Issue by dratchkov** [greg7mdp/sparsepp#13]
I am seeing this assertion:

sparsepp.h:3979: bool spp::sparse_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::_maybe_shrink() [......]: Assertion `(bucket_count() & (bucket_count()-1)) == 0' failed.

Any suggestion?

**Comment by greg7mdp** [comment]
That's odd! Can you share a piece of code that causes this assertion to occur? If not, I'll review the code anyways. Thanks for using sparsepp.

**Comment by dratchkov** [comment]
I did a printf("%lu\n", bucket_size()), got a 3290421856, printed just once.

This is part of a really large and convoluted code, I just can't extract a useful piece to reproduce the problem.

Let me know if you have some suggestions to debug. I'll try in the mean time to figure out what's hapenning.

-dave

**Comment by dratchkov** [comment]
here is backtrace from gdb:

#0  0x00002aaaac308925 in raise () from /lib64/libc.so.6
#1  0x00002aaaac30a105 in abort () from /lib64/libc.so.6
#2  0x00002aaaac301a4e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00002aaaac301b10 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000008b6f4a in spp::sparse_hashtable<std::pair<NdsInstance*, bool>, NdsInstance*, spp::spp_hash<NdsInstance*>, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SelectKey, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SetKey, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::_maybe_shrink (this=0xc3b023e8) at sparsepp.h:3980
#5  0x00000000008aee06 in spp::sparse_hashtable<std::pair<NdsInstance*, bool>, NdsInstance*, spp::spp_hash<NdsInstance*>, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SelectKey, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SetKey, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::_resize_delta (this=0xc3b023e8, delta=0) at sparsepp.h:4020
#6  0x00000000008af6f0 in spp::sparse_hashtable<std::pair<NdsInstance*, bool>, NdsInstance*, spp::spp_hash<NdsInstance*>, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SelectKey, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SetKey, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::_insert<spp::Two_d_iterator<std::pair<NdsInstance*, bool>, spp::sparsegroup<std::pair<NdsInstance*, bool>, spp::libc_allocator_with_realloc<std::pair<NdsInstance*, bool> > >*, std::pair<NdsInstance* const, bool>*, std::bidirectional_iterator_tag> > (this=0xc3b023e8, f=..., l=...) at sparsepp.h:4524
#7  0x00000000008a41f9 in spp::sparse_hashtable<std::pair<NdsInstance*, bool>, NdsInstance*, spp::spp_hash<NdsInstance*>, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SelectKey, spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::SetKey, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::insert<spp::Two_d_iterator<std::pair<NdsInstance*, bool>, spp::sparsegroup<std::pair<NdsInstance*, bool>, spp::libc_allocator_with_realloc<std::pair<NdsInstance*, bool> > >*, std::pair<NdsInstance* const, bool>*, std::bidirectional_iterator_tag> > (this=0xc3b023e8, f=..., l=...) at parsepp.h:4566
#8  0x000000000089b8cb in spp::sparse_hash_map<NdsInstance*, bool, spp::spp_hash<NdsInstance*>, std::equal_to<NdsInstance*>, spp::libc_allocator_with_realloc<std::pair<NdsInstance* const, bool> > >::insert<spp::Two_d_iterator<std::pair<NdsInstance*, bool>, spp::sparsegroup<std::pair<NdsInstance*, bool>, spp::libc_allocator_with_realloc<std::pair<NdsInstance*, bool> > >*, std::pair<NdsInstance* const, bool>*, std::bidirectional_iterator_tag> > (this=0xc3b023e8, f=..., l=...) at sparsepp.h:5163

**Comment by dratchkov** [comment]
This issue seems to have the result of iterators getting invalidated by insert. I will close it.
