### ISSUE TITLE
Using pointer as a key

### ISSUE THREAD

**Issue by dratchkov** [greg7mdp/sparsepp#14]
It seems that spp_hash depends on knowing the struct/class behind a pointer. I am using a 3rd party code that hides the object internals, so all I have are pointer to forward declaration of a class. As a result, taking sizeof(T) fails to compile.

 I hacked my copy to temporarily take sizeof(T*). Is this OK?

-dave

**Comment by greg7mdp** [comment]
Hi Dave,

Sorry I took so long to answer. The only reason that sparsepp takes sizeof(T) is to avoid having the lower bits of the hash value be all zeros. Your change is perfectly fine. I'll see if I can update the code to avoid dereferencing the pointer if all we have is a forward declaration.

**Comment by greg7mdp** [comment]
Issue is fixed, thanks for the report Dave.

**Comment by dratchkov** [comment]
Thanks for fixing this!
