### ISSUE TITLE
Emplace

### ISSUE THREAD

**Issue by springmeyer** [greg7mdp/sparsepp#15]
I noticed that `emplace` functionality is disabled (https://github.com/greg7mdp/sparsepp/blob/master/sparsepp.h#L4551-L4563). Any plans to re-enable this functionality? My motivation in asking is to be able to try sparsepp in place of `std::unorded_map` in C++11 code that is using `emplace`.

**Comment by greg7mdp** [comment]
Hey Dane, thanks for using sparsepp. Just added support for emplace(). Please let me know if you have any further issue.

**Comment by springmeyer** [comment]
Thank you @greg7mdp! I'll plan to test again and will file a new issue if I hit any problems.

**Comment by springmeyer** [comment]
Tested things out. Now hitting a problem with noncopyable objects. Created an issue at #16
