### ISSUE TITLE
Support for noncopyable objects

### ISSUE THREAD

**Issue by springmeyer** [greg7mdp/sparsepp#16]
I'm trying to add a noncopyable, but movable, object into `emplace()`. I've also tried `insert()`. Both return a compiler error like https://gist.github.com/springmeyer/503f8a842f8c9a09bccf21325c03c866. I'm seeing this with clang++ on OS X 10.11.

**Comment by springmeyer** [comment]
Here is a testcase: https://github.com/springmeyer/cxx-perf/tree/master. To replicate do:

```
git clone https://github.com/springmeyer/cxx-perf.git
cd cxx-perf
```

Uncomment these lines: https://github.com/springmeyer/cxx-perf/blob/master/insertion_speed.cpp#L100-L120

Then:

```
make
```
Should result in a compiler error. Am I doing something wrong?

**Comment by greg7mdp** [comment]
Thanks for reporting the issue and the test case. I'll look at it right away.

**Comment by springmeyer** [comment]
@greg7mdp sounds good, thank you.

**Comment by greg7mdp** [comment]
@springmeyer, I believe the issue is fixed. I tested it with clang 3.8 on ubuntu. It seems that sparsepp does not shine in your test of insertions, esp. with small tables.

**Comment by greg7mdp** [comment]
@springmeyer, found an issue in your test program. You were calling `m.reserve(iterations);` instead of `m.reserve(container_size);`. After fixing this, the results look better for sparsepp.

**Comment by springmeyer** [comment]
Thank you on both accounts. I confirmed it compiled now as well!

**Comment by greg7mdp** [comment]
Excellent, thanks for letting me know @springmeyer. Also I'd love to get some feedback of your experience with sparsepp, good and bad.

**Comment by springmeyer** [comment]
> Also I'd love to get some feedback of your experience with sparsepp, good and bad.

@greg7mdp Okay, will do! There are at least two open source projects I'm a maintainer on that depend on google sparsehash library. Because it has not seen a release for a long time I've been watching for alternatives. This is how I found your library.

Those two usages are of `sparsetable` (https://github.com/osmcode/libosmium/blob/master/include/osmium/index/map/sparse_mem_table.hpp#L42) and `dense_hash_map` (https://github.com/mapnik/mapnik/blob/master/include/mapnik/palette.hpp#L36) and not actually `sparse_hash_map` however. Do you have any plans to work on a new implementation of either `sparsetable` or `dense_hash_map`?

**Comment by greg7mdp** [comment]
@springmeyer, thanks a lot! I do not plan on providing a new implementation of `sparsetable` or `dense_hash_map` in  the near future. The `dense_hash_map` is not as interesting to me, as it does use a lot of memory, and I was attracted by the very low memory requirements of the `sparse_hash_map`... but then it is very fast. 

I just pushed a new version of sparsepp which adds support for std::reference_wrapper. After doing the emplace addition for you, I realized I should probably do this as well - it had been requested in the google sparsehash repository.

The official sparsehash maintainers were talking about supporting c++11, but it doesn't look like much is happening right now.

**Comment by springmeyer** [comment]
> I just pushed a new version of sparsepp which adds support for std::reference_wrapper.

👍 

> The dense_hash_map is not as interesting to me, as it does use a lot of memory

Yes, makes sense. I ended up using it in a situation were I needed the best possible speed. Maybe I will return to that question in the future...
