### ISSUE TITLE
Codestyle astyle/clang-format/uncrustify

### ISSUE THREAD

**Issue by denji** [greg7mdp/sparsepp#18]
Codestyle to reduce fragmentation code.

**Comment by greg7mdp** [comment]
Sorry, I do not understand what this issue is about.

**Comment by kirbyfan64** [comment]
I think he's saying to use a C++ formatting tool on the code base (like clang-format).

**Comment by greg7mdp** [comment]
@kirbyfan64, sounds reasonable, will do.

**Comment by greg7mdp** [comment]
I tried all three tools (astyle / clang-format / uncrustify) and I could not find one I was 100% happy with. In the end I mostly applied astyle's suggestions, but not every change. I used the following for astyle config:
```
--style=allman 
indent-continuation=0
indent-preproc-block
keep-one-line-blocks
keep-one-line-statements
```
