### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by lorenzhs** [greg7mdp/sparsepp#2]
You have a bunch of different licenses in the header of `sparsepp.h` and it's not really clear under which license sparsepp can be used. Could you please clarify that a bit? The ones in the file appear to be:

- SparseHash's BSD license
- Boost License for the Boost bits - very similar to BSD
- You added another instance of the BSD license, but it's not entirely clear to which parts of the code it apples. Is it only for your contributions or the entire code?

Am I correct in assuming that this means that the whole project is under the BSD license? If so, it'd be nice to mention this in the readme or maybe add a LICENSE file to the repo. The current situation is a bit confusing. Thanks a lot!

**Comment by greg7mdp** [comment]
That is a good point, I'll look into it, I'm not quite sure how these things work.

**Comment by greg7mdp** [comment]
Thanks again for the issue, I have added a LICENSE file for the repo and simplified somehow in sparsepp.h. Hopefully it is more clear now.

**Comment by lorenzhs** [comment]
Awesome, thank you!
