### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dratchkov** [greg7mdp/sparsepp#21]
Hi,

Seeing performance issue with finds for hash map <int, int> when inserting keys in order, either ascending or descending:
 
Testing sparse map                                                                                              
2000000 random inserts in 1 seconds                                                                             
2000000 random finds in 0 seconds                                                                               
2000000 random not-finds in 0 seconds                                                                           
2000000 sequential inserts in 0 seconds                                                                         
2000000 sequential finds in 0 seconds                                                                           
2000000 random not-finds in 19 seconds                                                                          
2000000 negative sequential inserts in 1 seconds                                                                
2000000 negative sequential finds in 0 seconds                                                                  
2000000 random not-finds in 17 seconds                                                                          

Testing STL map                                                                                                 
2000000 random inserts in 2 seconds                                                                             
2000000 random finds in 1 seconds                                                                               
2000000 random not-finds in 1 seconds                                                                           
2000000 sequential inserts in 1 seconds                                                                         
2000000 sequential finds in 0 seconds                                                                           
2000000 random not-finds in 0 seconds                                                                           
2000000 negative sequential inserts in 1 seconds                                                                
2000000 negative sequential finds in 0 seconds                                                                  
2000000 random not-finds in 0 seconds                   

Code is as follows:
void testSparseMap(int count) {
   spp::sparse_hash_map<int, int> s;
   time_t t;

   printf ("Testing sparse map\n");
   t = time (NULL);
   srand (0);
   for (int i = 0; i < count; ++i) { s.insert (make_pair(rand (), i)); }
   printf ("%d random inserts in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (0);
   for (int i = 0; i < count; ++i) { s.find (rand ()); }
   printf ("%d random finds in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (1);
   for (int i = 0; i < count; ++i) { s.find (rand ()); }
   printf ("%d random not-finds in %ld seconds\n", count, time (NULL) - t);

   s.clear ();
   s.reserve(0);
   t = time (NULL);
   srand (0);
   for (int i = 0; i < count; ++i) { s.insert (make_pair(i, i)); }
   printf ("%d sequential inserts in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (0);
   for (int i = 0; i < count; ++i) { s.find (i); }
   printf ("%d sequential finds in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (1);
   for (int i = 0; i < count; ++i) { s.find (rand ()); }
   printf ("%d random not-finds in %ld seconds\n", count, time (NULL) - t);

   s.clear ();
   t = time (NULL);
   srand (0);
   s.reserve(0);
   for (int i = 0; i < count; ++i) { s.insert (make_pair(-i, -i)); }
   printf ("%d negative sequential inserts in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (0);
   for (int i = 0; i < count; ++i) { s.find (-i); }
   printf ("%d negative sequential finds in %ld seconds\n", count, time (NULL) - t);

   t = time (NULL);
   srand (1);
   for (int i = 0; i < count; ++i) { s.find (rand ()); }
   printf ("%d random not-finds in %ld seconds\n", count, time (NULL) - t);
   s.clear ();
   s.reserve(0);
}

This is not an issue on Mac OS X.

**Comment by kmohanram** [comment]
unless i am misreading your code, you are inserting random keys with random hashes (assuming pass-through std::hash<int>), no? in my app, the hashes of the keys are in near-ascending order, i.e., i insert pairs of the form (a1,b1), (a2,b2), ... such that hash(a1) is 1, hash(a2) is 2, and so on ... (well, not exactly 1, 2, 3, ..., but pretty close). but still, i think that your test is very close to mine in terms of exposing something amiss in the sparsepp implementation.  if there is something to these very simple insertion strategies that sparseppp is choking on, it would be great to get that fixed.

**Comment by dratchkov** [comment]
@kmohanram Yes, sounds the same issue. This test does 3 passes - random numbers, ascending and descending. within each pass, it tests insertion, search-and-find and search-and-not-find (searching for non-existing keys). And that is where I see the runtime issue - very slow not-finds when the order is ascending/descending.

**Comment by greg7mdp** [comment]
@dratchkov Thanks for the test program. I'll look into it.

**Comment by greg7mdp** [comment]
@dratchkov - glad you reported this. I found the issue, and I'll fix it in sparsepp. 

When passing through sequential keys through the hash unchanged (as is currently the case), the entries in the hash table are all contiguous so when looking up a non-existent key it takes a long time to find an empty spot.

To workaround the issue for now, you can replace:

`spp::sparse_hash_map<int, int> s;`

with:

`spp::sparse_hash_map<int, int, Hasher32> s;`

where Hasher32 is defined as:

```
struct Hasher32 {
    size_t operator()(uint32_t k) const { return (k ^ 2166136261U)  * 16777619UL; }
};```

**Comment by dratchkov** [comment]
This worked, to the extent random and sequential inserts are now similar. But only now it gets similar to slightly worse results that Google's sparse_hash. dense_hash_map continues to dominate by far, in fact, it is actually faster than vector on insert :-)

Below result for 50M elements, with the same Hasher32.

Testing Google dense map                                                                                             
50000000 random inserts in 5 seconds                                                                            
50000000 random finds in 3 seconds                                                                              
50000000 random not-finds in 3 seconds                                                                          
50000000 sequential inserts in 2 seconds                                                                        
50000000 sequential finds in 2 seconds                                                                          
50000000 random not-finds in 3 seconds                                                                          
50000000 negative sequential inserts in 3 seconds                                                               
50000000 negative sequential finds in 1 seconds                                                                 
50000000 random not-finds in 3 seconds               
                                                           
Testing Google sparse map                                                                                            
50000000 random inserts in 27 seconds                                                                           
50000000 random finds in 14 seconds                                                                             
50000000 random not-finds in 14 seconds                                                                         
50000000 sequential inserts in 17 seconds                                                                       
50000000 sequential finds in 9 seconds                                                                          
50000000 random not-finds in 17 seconds                                                                         
50000000 negative sequential inserts in 16 seconds                                                              
50000000 negative sequential finds in 10 seconds                                                                
50000000 random not-finds in 18 seconds   
                                                                      
Testing sparse map                                                                                              
50000000 random inserts in 34 seconds                                                                           
50000000 random finds in 18 seconds                                                                             
50000000 random not-finds in 17 seconds                                                                         
50000000 sequential inserts in 54 seconds                                                                       
50000000 sequential finds in 9 seconds                                                                          
50000000 random not-finds in 9 seconds                                                                          
50000000 negative sequential inserts in 21 seconds                                                              
50000000 negative sequential finds in 3 seconds                                                                 
50000000 random not-finds in 5 seconds                  

Testing vector                                                                                                
50000000 random inserts in 10 seconds

**Comment by dratchkov** [comment]
Testing STL unordered_map                                                                                                 
50000000 random inserts in 27 seconds                                                                           
50000000 random finds in 8 seconds                                                                              
50000000 random not-finds in 9 seconds                                                                          
50000000 sequential inserts in 6 seconds                                                                        
50000000 sequential finds in 2 seconds                                                                          
50000000 random not-finds in 12 seconds                                                                         
50000000 negative sequential inserts in 6 seconds                                                               
50000000 negative sequential finds in 3 seconds                                                                 
50000000 random not-finds in 19 seconds

**Comment by greg7mdp** [comment]
Can you try sparsepp again, but with defining:

`#define SPP_NO_MIX`

before including sparsepp.h.

The vector insert should be faster than dense_hash_map. Did you reserve the space and use `vec[i] = value;`.

**Comment by greg7mdp** [comment]
I'll look into the differences. Please note that time() returns clock time and not a reliable way to measure performance.

**Comment by greg7mdp** [comment]
@dratchkov , I don't seem to get the same results as you do. Testing with Hasher32 in all cases, and after updating the test program to measure CPU time and not elapsed time, here is what I see:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./perftest1
Testing spp::sparse_hash_map
------------------------------
50000000 random inserts         in 20.86 seconds
50000000 random finds           in  6.76 seconds
50000000 random not-finds       in  6.74 seconds
50000000 sequential inserts     in 18.88 seconds
50000000 sequential finds       in  4.69 seconds
50000000 random not-finds       in  5.72 seconds
50000000 neg sequential inserts in 18.99 seconds
50000000 neg sequential finds   in  4.67 seconds
50000000 random not-finds       in  5.45 seconds

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./perftest1
Testing google::sparse_hash_map
------------------------------
50000000 random inserts         in 29.99 seconds
50000000 random finds           in 12.76 seconds
50000000 random not-finds       in 12.68 seconds
50000000 sequential inserts     in 16.23 seconds
50000000 sequential finds       in  7.16 seconds
50000000 random not-finds       in 16.53 seconds
50000000 neg sequential inserts in 16.32 seconds
50000000 neg sequential finds   in  7.02 seconds
50000000 random not-finds       in 16.46 seconds

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./perftest1
Testing google::dense_hash_map
------------------------------
50000000 random inserts         in  7.15 seconds
50000000 random finds           in  3.14 seconds
50000000 random not-finds       in  3.09 seconds
50000000 sequential inserts     in  3.35 seconds
50000000 sequential finds       in  1.21 seconds
50000000 random not-finds       in  3.41 seconds
50000000 neg sequential inserts in  3.35 seconds
50000000 neg sequential finds   in  1.21 seconds
50000000 random not-finds       in  3.47 seconds

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./perftest1
Testing std::unordered_map
------------------------------
50000000 random inserts         in 29.94 seconds
50000000 random finds           in 11.21 seconds
50000000 random not-finds       in 10.58 seconds
50000000 sequential inserts     in  9.65 seconds
50000000 sequential finds       in  6.27 seconds
50000000 random not-finds       in 19.57 seconds
50000000 neg sequential inserts in  9.42 seconds
50000000 neg sequential finds   in  5.27 seconds
50000000 random not-finds       in 19.99 seconds
```

**Comment by greg7mdp** [comment]
@dratchkov , I have updated the sparsepp default hash to add some key mixing. This solves the pathological case you exposed, where the keys are sequential and we are looking for non-existent keys. It also solves issue #17 reported by @kmohanram.

For both these cases, it is not necessary anymore to provide a custom hashing function, the default sparsepp hash works fine.

**Comment by greg7mdp** [comment]
@dratchkov, just to keep you upated, I have disabled the default key mixing in sparsepp, however yoy can enable it by defining SPP_MIX_HASH before including sparsepp.h.
