### ISSUE TITLE
sparse_hash_set seems slower and consumes more memory than Google sparsehash

### ISSUE THREAD

**Issue by stfairy** [greg7mdp/sparsepp#25]
My test code is as follows.

```cpp
#include <iostream>
//#include "sparsepp/sparsepp.h"
#include <sparsehash/sparse_hash_set>

int main() {
  int n = 1000000*200;

  //spp::sparse_hash_set<int> s;
  google::sparse_hash_set<int> s;

  for (int i = 0; i < n; i++) {
    s.insert(i);
  }
  std::cout << "done\n";

  //while (true) {}
  return 0;
}
```

```
$ uname -srvmpio
Linux 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
<snip>
$ g++ -O3 -o sparse_hash_set sparse_hash_set.cc
$ time ./sparse_hash_set
```

Sparsepp results:
```
real	0m30.069s
user	0m29.592s
sys	0m0.372s
```

Google Sparsehash results:
```
real	0m12.180s
user	0m11.884s
sys	0m0.180s
```

From the System Monitor and with the while loop uncommented, I was also able to find out the memory usage to be 1.6GB for Sparsepp and 911.8MB for Google Sparsehash.

**Comment by greg7mdp2** [comment]
Yes, your findings are correct, however:
1. your test program uses a very specific sequence of keys (all consecutive integers)
2. Google sparsehash just uses the integer key as the hash value (pass-through hashing)

This makes the insertion very fast, as there are no collisions. However, it makes finding that a key is not present in the set extremely slow. For that reason, I have chosen to not use pass-through hashing, even though it can look better in simple tests.

To see for yourself, you can add the following lines in your test program, after the insertion:

```c++
  size_t count = 0;
  for (int i = 0; i < n; i++)
      if (s.find(rand()) != s.end())
          ++count;
  printf("count = %zu\n", count);
  ```

This will demonstrate that the pass-through hashing, which looks very good on insertion-only tests, is probably not advisable in general.

**Comment by greg7mdp** [comment]
I don't advise to use pass-through hashing, but it can easily be done with sparsepp as well. For example define:

```c++
struct Hash32 {
   size_t operator()(uint32_t k) const { return k; }
};
```

and your set as: `spp::sparse_hash_set<int, Hash32> s;`

You will see that the insertion is now faster than with Google's sparse_hash_set, and that the memory usage is reduced to ~1.2GB, still a little bit more than Google's version.

However the lookup of non-present keys will be very slow, so it is probably not a very good idea.

**Comment by greg7mdp** [comment]
Closing the issue, please reopen is you still have some questions.
