### ISSUE TITLE
Doesn't compile on Mac using clang and C++03

### ISSUE THREAD

**Issue by jhetherly** [greg7mdp/sparsepp#26]
First of all, thank you for writing an outstanding implementation of a hash table. It really saved my bacon ;)

I have one small problem that I was able to easily work around, but wanted to recommend a fix in case anyone else sees the same issue.

I originally tried compiling this using clang on my Mac without C++11. This failed because clang defines similar macros to gcc and this confuses the preprocessor logic found here
https://github.com/greg7mdp/sparsepp/blob/master/sparsepp.h#L892
and here
https://github.com/greg7mdp/sparsepp/blob/master/sparsepp.h#L905.
It boils down to not being able to locate the tr1 header. I fixed this by switching the order of the preprocessor if statements (i.e. checking for clang before gcc).

**Comment by greg7mdp** [comment]
Glad you like it, and thank you very much for the suggestion, I just implemented it.
