### ISSUE TITLE
Ordering with hash collisions

### ISSUE THREAD

**Issue by indigox4** [greg7mdp/sparsepp#28]
Hello,

Just curious, if I insert multiple elements into a sparse_hash_set that hash to the same value, is there some specific ordering the elements will take if I iterate over all of the items using
```
for( auto it = set.begin(); it != set.end(); ++it )
```

Is there any way I can specify that ordering? (with a custom less-than function or something?)

**Comment by greg7mdp** [comment]
Hi Stephen,

Well, there is a specific ordering, but nothing that can be relied upon or overridden. The collisions are resolved in sparsepp with an open addressing scheme ([Quadratic Probing](https://en.wikipedia.org/wiki/Quadratic_probing)), so entries with the same hash value will be spread out over the sparse table.

When iterating over the set, entries with the same hash value will not even be grouped together, let alone sorted.

**Comment by indigox4** [comment]
Ok, makes sense, thanks Greg!
