### ISSUE TITLE
how to do std-style contains?

### ISSUE THREAD

**Issue by sam0x17** [greg7mdp/sparsepp#33]
I need to check if an `spp::sparse_hash_map` contains a particular key. Following the usual logic I would do with `std::unordered_map<T, T>`, it would be something like this:

```C++
spp::sparse_hash_map<T1, T2> map;
// ...
T1 some_key;
auto got = map.find(some_key);
if(got == map::end()) {
  // do something
}
```

However I am getting a super long error saying that the types for `got` and `map::end()` are incompatible. I tried a number of variations of this and always get the same error. I suspect this has something to do with the double definition of `find()` with const and non const iterators, but I have no idea how to get around it. Just need to do a simple contains check...

**Comment by sam0x17** [comment]
P.S. would LOVE it if there was a `bool contains(T key)` method built into all the sparsepp classes. It's annoying as hell that `std::` doesn't offer this.

**Comment by greg7mdp** [comment]
Hi Sam,

I just tried it and it seems to work fine. Here is my code:
```
#include <iostream>
#include <sparsepp/spp.h>
 
int main()
{  
    spp::sparse_hash_map<int,char> example = {{1,'a'}, {2,'b'}};
 
    auto got = example.find(2);
    if (got == example.end()) {
        std::cout << "Not found\n";
    }
    else {
        std::cout << "Found " << got->first << " " << got->second << '\n';
    }
}
```

and the output:

```
$ g++ -O2 -std=c++11 -I.. -Wall -pedantic -Wextra -D_XOPEN_SOURCE=700  -DNDEBUG find.cc -o find
$ ./find
Found 2 b
```

Could you post a full sample program that doesn't compile?

Thanks,

greg

**Comment by greg7mdp** [comment]
Also, what compiler are you using?

**Comment by greg7mdp** [comment]
Sam, I just added `bool contains(const T& key) const;` just for you.

**Comment by sam0x17** [comment]
Hey thanks a bunch -- I use `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

**Comment by greg7mdp** [comment]
Oh, I see the typo. You wrote `map::end()` instead of `map.end()`.

**Comment by sam0x17** [comment]
omg thanks!
