### ISSUE TITLE
A way to configure default capacity

### ISSUE THREAD

**Issue by sam0x17** [greg7mdp/sparsepp#35]
This is one thing I would like to set, maybe in the constructor. I assume it already defaults to 0 capacity until there are elements, but I also want the ability to configure the initial size once there are elements.

**Comment by greg7mdp** [comment]
You can set an initial size with the first parameter of the constructor. For example:

```spp::sparse_hash_set<int> myset(100000);```

Is that what you were looking for?

**Comment by sam0x17** [comment]
yup -- thanks!
