### ISSUE TITLE
shrink to fit

### ISSUE THREAD

**Issue by meox** [greg7mdp/sparsepp#36]
Is there somenthing like shrink_to_fit like we have for std::vector?
I tried to use **clear** and **reserve(0)** but the memory is not released.

Thanks

**Comment by greg7mdp** [comment]
clear() definitely releases the memory. Depending on the platform you are using (Windows?), you may not notice that the memory has been freed, but it has. For example if, after calling clear(), you create a second hash table with the same elements, the memory usage should not increase.

**Comment by meox** [comment]
I'm using Linux and Solaris.
The behaviour, respect to memory management, is very similar to `std::unordered_map`:
seems that the memory is not released to OS after a clear. This is correct in many scenarios but there are some cases that could be usefull to clear and release all the memory back to OS.

**Comment by Bu11etmagnet** [comment]
No C++ standard library class or function returns memory "back to the OS". The best C++ classes/methods can do is call delete (which is likely to call free), releasing memory back to the dynamic memory allocator. Whether the dynamic memory allocator releases the memory back to the OS is an implementation detail, not visible from C++.

**Comment by meox** [comment]
ok thanks for this clarification
