### ISSUE TITLE
Question about un-expectedly *good* speed

### ISSUE THREAD

**Issue by rob-p** [greg7mdp/sparsepp#4]
Hi Greg,

  First, thanks for this excellent hash table!  I've been wanting something like this for some time, as I find the standard unordered_map in C++ to be reasonably fast, but with *very poor* memory use.  The balance struck by sparsepp is near-perfect, and it's a near drop-in replacement for unordered_map which makes it very easy to use.  I'm seeing something that, to me, is completely unexpected.  I have a project, [RapMap](https://github.com/COMBINE-lab/RapMap/tree/develop-salmon), where I want to replace a Google dense_hash_map with the sparsepp sparse_hash_map to reduce memory usage.  I've been doing some benchmarking to see what type of speed hit I would have to take in my particular scenario (the memory usage with sparsepp is already a factor of 2 lower).  I got some *very* unexpected results.  Specifically, sparsepp seems to be working faster than the Google dense_hash_map.  I'm attaching a timing plot and some `/usr/bin/time` results for your perusal.

![timing](https://cloud.githubusercontent.com/assets/361470/18253345/f6c36276-7361-11e6-84c8-ed4788d2a4d7.png)

This image shows the total elapsed time (wall clock time) for each dataset using the google dense_hash_map (dense) and the sparsepp sparse_hash_map (sparse).  Interestingly, you can see that sparsepp almost always outperforms the dense_hash_map.  Now, my workload isn't entirely looking up hash keys, but no other code here changed apart from which hash was being used for the lookup, so that is the only thing to which I can attribute the timing difference.  Also very interesting to me is the actual timing logs: 

[timing.zip](https://github.com/greg7mdp/sparsepp/files/455359/timing.zip)

the thing that is interesting to me here is the difference in user, system and elapsed time, and the total CPU usage.  For each run, I told the process to use 16 threads.  The hashing workload here is *completely* lookups (i.e. there are no insertions or deletions during these runs, apart from the initial de-serialization of the hash from disk).  It looks like sparsepp is consistently coming closer to the pre-specified cpu usage percentage (often 1,300-1,500% compared to the 1,000-1,200% with dense_hash_map).  It also appears that sparsepp is consistently consuming more user time and less system time than google's dense_hash_map.

Do you have any idea why I might be seeing these un-expected performance characteristics?  Any light you could shed on *why* I might see this would be greatly appreciated!

Thanks,
Rob

**Comment by greg7mdp** [comment]
Hi Rob,

First, thank you very much for the feedback. It is good to hear about others using sparsepp!

Indeed, the search for better memory use is what lead me to work on sparsepp. At work, I found that unordered_map and other hash tables were crippling the size of models I could use, especially when they resize and the memory usage goes through the roof, so I had been using cpp-btree, but lookup performance is poor.

The beauty of Google's sparse hash design (and sparsepp) is that not only they have a tiny memory overhead, but also there is only a very small bump in memory usage when resizing. With sparsepp, I was very happy to match the memory usage profile of cpp-btree, but be faster than unordered_map.

Now about the performance results you see. I think the reason for sparsepp lower system time is likely the fact that it uses less memory, and therefore may have less cache misses, and also less minor page faults (I looked at a couple of the timings results you sent, and sparsepp always had significantly less minor page faults). Neither sparsepp or dense_hash_map make any explicit system call on lookup.

As for the fact that it uses more user time, it is expected as sparsepp needs to do some bit operations to figure out which entries of the sparsetable are occupied. It is possible to optimize these bit operations if you know that your executable will only be run on somewhat recent processors which support the hardware popcnt instruction. If that is the case, make sure to compile with the option `"-mpopcnt"`.

Additionally, depending on the hash value you provide, and how well it is distributed over the low order bits, it is possible that sparsepp does a better job than dense_hash_map at utilizing these hash values (that is if you are using my version after the Aug 30th commit).

Again, thanks for the feedback, and I'll be happy to try to answer any further question you have.

**Comment by romange** [comment]
@rob-p Sorry for jumping in... Please make sure that your system does not use swap memory at all. Having swap disk might skew any benchmark.  As @greg7mdp pointed out neither of those libraries use system calls so you should not see any system time in your load test. 

As a side note: for use-cases where you need to load a table once and use mostly lookups afterwards you might prefer using *cuckoo* hash map. It will provide better! memory characteristics than sparse hashmap and better! times than dense hashmap.

**Comment by rob-p** [comment]
Hi @romange,

  No swap was being used here.  This was a set of benchmarks using either 5.5G (dense_hash_map) ore 2.6G (sparsepp sparse_hash) on a system with 256G of physical memory.  It's a multi-core system (24 cores), so it's possible there was some thread migration etc. going on in the background, but I performed the tests under a "typical" scenario.

  I'm very interested in the cuckoo hash map you mention. Actually, I use a [*concurrent* cuckoo hash map](https://github.com/efficient/libcuckoo) in [another one of my projects](https://github.com/COMBINE-lab/salmon).  Do you have a particular library / implementation in mind?  I care most about memory usage while building the map (inserts don't need to be blazing fast, but sparsepp's memory scaling performance when building the initial map is *amazing*) and then about lookup performance.  The use-case is that I build what is essentially an inverted index (mapping short sub-strings to intervals of a suffix array) once, for a reference text, and then for many different data sets, I read in this index and do many (100s of millions or billions) of lookups.

**Comment by romange** [comment]
Could you point me to the code that builds this inverted index? Do you use
std::string as a key?

**Comment by rob-p** [comment]
@romange, the function that builds this inverted index is [here](https://github.com/COMBINE-lab/RapMap/blob/develop-salmon/src/RapMapSAIndexer.cpp#L251).  I don't use strings as keys.  Since I'm building the index over a small alphabet (the input string is DNA (actually, RNA) and the alphabet is {A,C,G,T}), I first 2-bit encode the string and then store each key as a 64-bit integer (meaning the strings can never be > 32 characters, but this is **ok** in my context).

**Comment by romange** [comment]
@rob-p hmm, your keys and values are small POD types and your hash function is good. I do not see any reason why dense hash table would be slower than sparse table. One advice I could tell you is not to use `find` to check if a key already exists and then to use`operator[]` for insertion sequence.
You can save ~50% cpu work by using `auto res = insert(...)` (or convenient emplace in cxx11) and to test `res.second` whether the insertion took place or not. This will be equivalent in what you are trying to achieve.

@greg7mdp Is it correct to assume that sparsepp still needs to consume x3 more space during growth cycle? 

If it's correct then https://github.com/romange/beeri/blob/master/base/cuckoo_map.h is also worth checking. It will be slower during inserts but its Lookups will be very fast. In fact they are faster than of dense_hash_map on my benchmarks. This is due to the fact that cuckoo hash map has `O(1)` lookup complexity and on average reads 1.5 cache lines. My cuckoo map has limitations that it can only map uint64 to POD type (was too lazy to make it fully generic) but it fits your scenario.

**Comment by greg7mdp** [comment]
@romange the answer to your question is no, sparsepp will _not_ need 3x more memory when resizing, unlike dense_hash_map or most other hash tables. If you look at the writeup in bench.md, this is described there and the main reason why sparsepp can take so many more entries. There is a tiny memory usage bump for sparsepp  when resizing, maybe 1.1x to 1.2x.
You are correct that sparsepp does not use a single bucket array, but multiple blocks.

**Comment by romange** [comment]
@greg7mdp Your sparsepp is an excellent data structure which brings the state-of-art of hash table development a step forward!

I've read your explanation about block structure at https://github.com/greg7mdp/sparsepp/blob/master/sparsepp.h#L2270

Does it mean that you have an allocation per block? i.e. sparsepp that needs to contain 32M records will need to store 1M pointers as well?  It seems to me that you do something better with that using _init_alloc_batch_sz but it's not clear to me...

**Comment by greg7mdp** [comment]
@romange thanks for the kind words! I have to credit Google developers (I think originally Craig Silverstein) for the idea and original implementation. I was very impressed with the design and just tried to improve it so performance was better.
You are correct there is one memory allocation per sparsegroup (each can contain as many as 32 entries). As the sparse table resizes when it is 50% full, on average there will be 16 records per sparsegroup, so for 32M records that would be 2M pointers.  Still, that works out to only 1/16th of a pointer, or 4 bits of memory usage per entry, which is not very much.
The _init_alloc_batch_sz() does not change that, it only reduces the number of memory allocations (or realloc) when inserting items into the table.. by allocating larger buffers when the first entry of a sparsegroup is inserted. This makes the insertion faster, but uses slightly more memory, especially if the hash function is poorly distributed.

**Comment by greg7mdp** [comment]
As much as I enjoy seeing this issue title, I guess I still need to close it.
