### ISSUE TITLE
Support for search with compatible key types

### ISSUE THREAD

**Issue by brenoguim** [greg7mdp/sparsepp#41]
First of all, congrats on this awesome hash map :) It's far better than others that I've tried.

One thing that I implemented locally is the ability to search on the sparse_hash_set, using a different key. Of course, you have to also pass in a compatible hash functor and comparison hash functor.

This is the original code in the use case:

```
spp::sparse_hash_map<unsigned, Car*> my_cars = produce();

// I can query cars by their Ids
unsigned cid = some_car_id();
bool got_it = my_cars.find(cid) != my_cars.end();

for (auto& p : my_cars) {
    Car* c = p.second;
    print(c); // I can iterate by car pointers as well!
}
```
So, instead of having a map of Id to Car, I could just have a set of cars:

```
struct Functor {
    std::size_t operator()(const Car* c) const { return c->id(); }
    bool operator()(const Car* c1, const Car* c2) const { return c1 == c2; } // its ok, car address is valid identity too
};

spp::sparse_hash_set<Car*, Functor> my_cars = produce();

// I can query cars by their Ids
struct CompatibleFunctor {
    std::size_t operator()(unsigned id) const { return id; }
    bool operator()(const Car* c1, unsigned c2) const { return c1->id() == c2; }
} cfunctor;

unsigned cid = some_car_id();
bool got_it = my_cars.find(cid, cfunctor, cfunctor) != my_cars.end();

for (auto& c : my_cars) {
    print(c); // I can iterate by car pointers as well!
}
```
So I get the same functionality but my hashtable items are half the size (which is my real goal with all this really).

Would you be willing to accept some form of implementation of this functionality as a pull request? Just thought I should check before writing the code in a shareable way.

**Comment by greg7mdp** [comment]
Could you instead do something like this:

```
struct Car
{
    Car(unsigned _id) : id(_id) {}

    bool operator==(const Car &o) const  {  return id == o.id;  }

    unsigned id;
    std::string brand;
    std::string model;
};

namespace std
{
// inject specialization of std::hash for Car into namespace std
// ----------------------------------------------------------------
template<>
struct hash<>
{
    std::size_t operator()(Person const &p) const { return id; }
};
}

int main()
{
    // As we have defined a specialization of std::hash() for Person,
    // we can now create sparse_hash_set or sparse_hash_map of Persons
    // ----------------------------------------------------------------
    spp::sparse_hash_set<Car> cars;

    if (cars.find(Car(22)) != cars.end())
        ; // car of id 22 found
}
```

**Comment by brenoguim** [comment]
Yeah, I hoped I could do something like that. But in my application, the object itself is quite large, so creating one Car just to query for a car is a prohibitive cost. Actually, I don't think I even have access to the constructor.

I get those cars from external library.

By the way, this API is not my idea. If it helps, this comes from boost::unordered_set:

http://www.boost.org/doc/libs/1_63_0/doc/html/boost/unordered_set.html
```
        template <class CompatibleKey, class CompatibleHash,
            class CompatiblePredicate>
        const_iterator find(
                CompatibleKey const&,
                CompatibleHash const&,
                CompatiblePredicate const&) const;

Returns: | An iterator pointing to an element with key equivalent to k, or b.end() if no such element exists.
-- | --
Notes: | The templated overloads are a non-standard extensions which allows you to use a compatible hash function and equality predicate for a key of a different type in order to avoid an expensive type cast. In general, its use is not encouraged.
```

**Comment by greg7mdp** [comment]
Thanks for explaining. I'll be happy to integrate a pull request for the missing functionality, esp. it it follows a pattern already existing in boost::unordered_set.

**Comment by brenoguim** [comment]
Cool. I never contributed via github, but I'll give it a try. The code is simple, but I gotta know the test framework a bit better first.

**Comment by greg7mdp** [comment]
This new library (https://github.com/Tessil/sparse-map) seems to accept any type that the "hash" and "equal" functors accept (see "Heterogeneous lookups" at the end of the README). Could you implement something similar?

**Comment by greg7mdp** [comment]
I don't plan on implementing this in sparsepp, but that feature is available in my [parallel_hashmap](https://github.com/greg7mdp/parallel-hashmap) which I think is a better hash map implementation. I would recommend you switch to it.
