### ISSUE TITLE
Reference invalidation on insert

### ISSUE THREAD

**Issue by Smattr** [greg7mdp/sparsepp#45]
I'm trying to debug a problem of my own making. In attempting to use sparsepp as a drop-in replacement for `std::unordered_set` in a [model checker](https://en.wikipedia.org/wiki/Model_checking), I ran into some unexpected memory corruption. The code can be distilled to something like the following self-contained reproducer:

```c++
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <iostream>
#include <queue>
#include <unistd.h>

#ifdef USE_SPARSEPP
  #include <sparsepp/spp.h>
  template<typename... Args>
  using set = spp::sparse_hash_set<Args...>;
#else
  #include <unordered_set>
  template<typename... Args>
  using set = std::unordered_set<Args...>;
#endif

struct State {
  uint8_t value = 0;

  // XXX: When using std::unordered_set, this can be
  //  const State *const previous = nullptr;
  const State *previous = nullptr;

  State() {}

  State(const State *s): value(s->value), previous(s) {}

  // XXX: When using std::unordered_set, assignment does not need to be implemented
  State &operator=(const State &other) {
    value = other.value;
    previous = other.previous;
    return *this;
  }

  bool operator==(const State &other) const noexcept {
    return value == other.value;
  }
};

namespace std {
  template<>
  struct hash<State> {
    std::size_t operator()(const State &s) const noexcept {
      return static_cast<std::size_t>(s.value);
    }
  };
}

static void print_trace(const State &s) {
  if (s.previous != nullptr)
    print_trace(*s.previous);
  std::cout << "value == " << unsigned(s.value) << "\n";
}

int main(void) {

  set<State> seen;
  std::queue<const State*> pending;

  State init;
  auto it = seen.insert(init);
  assert(it.second);
  pending.push(&*it.first);

  while (!pending.empty()) {

    const State *s = pending.front();
    pending.pop();

    State next(s);
    next.value++;

    if (next.value == 42) {
      std::cout << "Failed. Trace:\n";
      print_trace(next);
      return EXIT_FAILURE;
    }

    auto it = seen.insert(next);
    if (it.second) {
      pending.push(&*it.first);
    }
  }

  return EXIT_SUCCESS;
}
```

which can be compiled with:

```sh
# Build with std::unordered_set
g++ -std=c++11 -W -Wall -Wextra -Werror main.cc

# Build with sparsepp
g++ -DUSE_SPARSEPP -std=c++11 -W -Wall -Wextra -Werror main.cc
```

This runs correctly (produces the expected failing trace) when using `std::unordered_set` but triggers segfaults with `spp::sparse_hash_set`. It seems fairly likely to me that the problem stems from retaining a pointer into the set (`pending.push(&*it.first);`), and my following comments are assuming this is the case.

The sparsepp readme has this to say:

> # Warning - iterator invalidation on erase/insert
> ...
> 2. inserting new elements is likely to invalidate iterators (iterator invalidation can also happen with std::unordered_map if rehashing occurs due to the insertion)

The last part of this is surprising to me. I was under the impression `std::unordered_set` iterators and references remained valid after insertion. Not authoritative, but [cppreference claims this is true before C++17](http://en.cppreference.com/w/cpp/container/set/insert). Is this not correct? Also the sparsepp readme doesn't explicitly mention that references are invalidated (though thinking about the implementation it is straightforward to see that this is probably the case and the motivation for this).

All in all, I don't think this is a sparsepp bug, but I wanted to understand whether I was doing something incorrect here or misreading the sparsepp docs.

**Comment by greg7mdp** [comment]
Hi, and thanks for the report. The [link](http://en.cppreference.com/w/cpp/container/set/insert) you posted regarding references remaining valid is a link to the std::set documentation (not unordered_set).
The [unordered_set](http://en.cppreference.com/w/cpp/container/unordered_map/insert) documentation states:
`If rehashing occurs due to the insertion, all iterators are invalidated. Otherwise iterators are not affected. References are not invalidated.`

So you are correct that the guarantee that references are not affected by insert() is broken by sparsepp, and should be mentioned in the readme.

**Comment by Smattr** [comment]
Thanks for the quick reply! And thanks for the clarifying commit.
