### ISSUE TITLE
Working with Classes

### ISSUE THREAD

**Issue by nathangeorge1** [greg7mdp/sparsepp#46]
Hello,

Great work. How do I make this work with a user-defined class?

Thanks,
Nathan

**Comment by greg7mdp** [comment]
Thanks! For the user defined class, see hast_std.cc in the examples directory.

**Comment by nathangeorge1** [comment]
Thanks for this: https://github.com/greg7mdp/sparsepp/blob/master/examples/hash_std.cc

But instead of creating a new struct, i was interested in mapping 2 previously defined classes. Is there something I could add to the classes to have them work with sparsecpp?

**Comment by greg7mdp** [comment]
Hum, I'm not sure I understand the question. You can create a sparse_hash_map of two classes of course. You'd have to provide a hash function for the class used as a key, like in the example I sent. What problem are you having?

**Comment by nathangeorge1** [comment]
I might not understand C++ enough, but in this part:

![image](https://user-images.githubusercontent.com/2744891/34162857-2abef136-e4a3-11e7-88a2-b96c801faabf.png)
it appears that you're initializing the hash set with strings, but would this example work if you initialized it with the actual `Person`?

I'm interested in doing something like `spp::sparse_hash_map<cv::Point, MyData> map;`

**Comment by greg7mdp** [comment]
> I'm interested in doing something like `spp::sparse_hash_map<cv::Point, MyData> map;`

That shouldn't be a problem... go for it :-)

**Comment by nathangeorge1** [comment]
cool I'll try it out

**Comment by nathangeorge1** [comment]
I tried various things, but I could not get spp::sparse_hash_map to work with classes. Could you show me an example of how to get this to compile?

![image](https://user-images.githubusercontent.com/2744891/34498880-88c2703a-efd1-11e7-8c6a-56ff1cf8cf2d.png)

**Comment by OvermindDL1** [comment]
> I tried various things, but I could not get spp::sparse_hash_map to work with classes. Could you show me an example of how to get this to compile?

What error did you get?  Did you create a hasher for `cv::Point`?

**Comment by nathangeorge1** [comment]
I was not able to create a hasher for `cv::Point` because the hash_std.cc example only works for structs. I tried replacing "struct" with "class" but it just threw a bunch of errors, probably cause I'm not sure what I'm doing.

**Comment by OvermindDL1** [comment]
> I was not able to create a hasher for cv::Point because the hash_std.cc example only works for structs.

A class is a struct in C++, they just have different default visibility of their fields/methods.

What code did you try and what errors did you get?  The hasher can stay a struct, that's fine, but it is hard to diagnose without actually seeing both your complete executable code and/or the complete errors.  :-)

**Comment by nathangeorge1** [comment]
Actually I tried it again and this time I made half progress.

This code compiled and ran:

```C++
// General Includes
#include <stdlib.h>
#include <string>
#include <iostream>
#include <stdio.h>
#include <ostream>
#include <vector>

// ROS Includes
#include "ros/ros.h"

// OpenCV Includes
#include <opencv2/core.hpp>

// Project Includes
#include "utility/class_utils/Overload.hpp"
#include "utility/data_structures/sparsepp/spp.h"

// Namespaces
using namespace std;
using namespace cv;
using std::string;

namespace std
{
// inject specialization of std::hash for Person into namespace std
// ----------------------------------------------------------------
template<>
struct hash<cv::Point>
{
	std::size_t operator()(cv::Point const &p) const
	{
		std::size_t seed = 0;
		spp::hash_combine(seed, p.x);
		spp::hash_combine(seed, p.y);
		return seed;
	}
};
}

/** @file
 *  @brief testbed for learning C++
 */
int main( int argc, char** argv ) {
	// init
	ros::init(argc, argv, "trial");
	ros::NodeHandle nh;

	// As we have defined a specialization of std::hash() for Person,
	// we can now create sparse_hash_set or sparse_hash_map of Persons
	// ----------------------------------------------------------------
	spp::sparse_hash_map<cv::Point, cv::Point> map =
		{
			{ { 1, 2 }, {3, 4}}
		};

	// printing
	for (auto& p: map)
		std::cout << p.first << ' ' << p.second << '\n';

	// accessing
	// ?

	return EXIT_SUCCESS;
}

```
with the following output:
![image](https://user-images.githubusercontent.com/2744891/34538340-094abbae-f09a-11e7-9b7f-322b692f2532.png)

But as you can see at the very end, I do not know how to access an individual mapping because the index is a `cv::Point`, and it appears to only take integers and strings, as in this example on your README:

![image](https://user-images.githubusercontent.com/2744891/34538257-bc925b78-f099-11e7-87c1-7fce8894def3.png)

Is there a way that the index can be a class?

**Comment by greg7mdp** [comment]
try std::cout << map[cv::Point(1, 2)] << '\n";

**Comment by OvermindDL1** [comment]
> try std::cout << map[cv::Point(1, 2)] << '\n";

Yep this.  Remember, whatever the key is, is what you pass in to get the value back out.

**Comment by nathangeorge1** [comment]
thanks @greg7mdp; that worked

Also, how would I attempt to initialize `spp::sparse_hash_map<cv::Point, cv::Point> map` with actual cv::Points instead of inputting the raw values?

**Comment by greg7mdp** [comment]
just do: map[point1] = point2;

**Comment by nathangeorge1** [comment]
Yes that worked for publicly accessible members; thanks.

I spent some time trying to get it working with my own class using private members, and I thought I'd share how I did it if anyone else would like to do it as well.

Here is the code:

```C++
// General Includes
#include <stdlib.h>
#include <string>
#include <iostream>
#include <stdio.h>
#include <ostream>
#include <vector>

// ROS Includes
#include "ros/ros.h"

// OpenCV Includes
#include <opencv2/core.hpp>

// Project Includes
#include "utility/class_utils/Overload.hpp"
#include "utility/data_structures/sparsepp/spp.h"
#include "utility/data_types/TrimPoint.hpp"

// Namespaces
using namespace std;
using namespace cv;
using std::string;

namespace std
{
// inject specialization of std::hash for Person into namespace std
// ----------------------------------------------------------------
template<>
struct hash<TrimPoint>
{
	std::size_t operator()(TrimPoint const &p) const
	{
		int angle = p.getAngle();
		int speed = p.getSpeed();
		std::size_t seed = 0;
		spp::hash_combine(seed, angle);
		spp::hash_combine(seed, speed);
		return seed;
	}
};
}

/** @file
 *  @brief testbed for learning C++
 */
int main( int argc, char** argv ) {
	// init
	ros::init(argc, argv, "trial");
	ros::NodeHandle nh;

	// As we have defined a specialization of std::hash() for Person,
	// we can now create sparse_hash_set or sparse_hash_map of Persons
	// ----------------------------------------------------------------
	spp::sparse_hash_map<TrimPoint, TrimPoint> map;
	TrimPoint p1(1,2,3,4,true,5);
	TrimPoint p2(6,7,8,9,false,10);
	map[p1] = p2;

	// printing
	for (auto& p: map) {
		TrimPoint first = p.first;
		std::cout << first << endl;
	}

	// accessing
	cout << map[p1] << endl;

	return EXIT_SUCCESS;
}
```

1. Note the use of getters in the hasher.
2. Remember to make the getters [const correct](https://stackoverflow.com/questions/5973427/error-passing-xxx-as-this-argument-of-xxx-discards-qualifiers/5973485)
3. Don't forget to overload ==; my code looks like:
4. the class needs a default constructor

```C++
	bool operator==(const TrimPoint &other) const {
		return (this->x == other.x && this->y == other.y && this->z == other.z);
	}
```

I would suggest, if you agree, to update your README's "Example 2 - providing a hash function for a user-defined class" with these 4 instructions for classes, as a lot of people are like me, in that they don't really know the differences between classes/structs or sets/maps, nor how to fix these build errors.

Thanks for all your help @greg7mdp. It was very helpful, and I'll now probably be using your hashmap quite often in 2 robotic startups.

Regards,
Nathan

**Comment by OvermindDL1** [comment]
> I spent some time trying to get it working with my own class using private members, and I thought I'd share how I did it if anyone else would like to do it as well.

The proper way would be to make the hasher a friend of the main class, then it could access the private fields.  ^.^

If you can do it via public access though, that is *always* preferred.

**Comment by greg7mdp** [comment]
Thank you for the help @OvermindDL1, your assistance is greatly appreciated!

**Comment by greg7mdp** [comment]
@nathangeorge1, I tried to make the example as simple as possible. I assume most users of sparsepp are experienced in C++ and would know what to do when switching to a class, but I definitely could - and will -
 add another example with a class. Thanks for the suggestion.
