### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [greg7mdp/sparsepp#49]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by greg7mdp** [comment]
What about you create the package and I'll add it? Would that work for you?

**Comment by ZaMaZaN4iK** [comment]
i think i can add package for the library to Bincrafters repo.

**Comment by ZaMaZaN4iK** [comment]
https://github.com/bincrafters/conan-sparsepp/tree/testing/1.1

**Comment by greg7mdp** [comment]
@ZaMaZaN4iK , I have no idea what to do with that? Close the issue?
