### ISSUE TITLE
Multiply defined symbol

### ISSUE THREAD

**Issue by rob-p** [greg7mdp/sparsepp#5]
Hi Greg,

  When I compile (g++ 4.9.1) with the current `sparsepp.h` I get a multiply-defined symbol `void cpuid(int*, int)`.  It's not clear to me why this happens, as sparsepp seems to be properly include guarded, and the pre-processor directives should prevent the function from being defined more than once.  However, no re-arrangement of the headers seems to rectify this problem, and I don't have any other includes that seem to be defining this symbol (i.e. all definitions are coming from sparsepp).  I'm able to rectify the issue by simply changing the call to `cpuid` to be a call to the underlying `__cpu_count` function (my downstream software explicitly *doesn't* support windows, so I don't need to worry about that codepath) — but this solution seems like a hack.  Any idea why I might be seeing this behavior or how I might rectify it cleanly?

**Comment by greg7mdp** [comment]
Thanks for the issue. Indeed it is not a very good idea to define a function named `cpuid()` in the global scope, so I renamed it `spp_cpuid()`. I believe it should resolve your issue.
