### ISSUE TITLE
didn't measure difference on stock exchange HFT data stream

### ISSUE THREAD

**Issue by steven-varga** [greg7mdp/sparsepp#50]
Liked the drop-in replacement feature, and the header only format. Indeed all was needed to copy and define the map. 
Used it to hash 8byte stock symbols to incremented integers, where the symbol set was around 6000 with 6e7 - 8e7 even count per day x 5 years.  Profiled the code with gprof and didn't find difference between hash_map, unordered_map, and your implementation. 
Either 
1) I was doing something not right
2) this was a corner case 
3) should find a good hash function, then compare again?
wishing you best: steven

**Comment by greg7mdp** [comment]
Hi @steven-varga. To help me understand exactly what your use case is, can you post the declaration of the  sparse_hash_map that you used? Thanks!

**Comment by steven-varga** [comment]
Yes indeed: it is about speed as opposed to footprint. 
` spp::sparse_hash_map<std::string, uint64_t> map1;` or ` spp::sparse_hash_map<uint64_t, uint64_t> map2;` 
Then I used `auto it = map.find( key ); ` and inserted new ones upon failure.
The profiling showed the code path spends 50% on hash lookups, I tried a quick drop in, and didn't notice difference.

**Comment by greg7mdp** [comment]
Ah, sparsepp is mostly about footprint, especially when inserting entries and resizing occurs (high water mark). Should be a little bit faster, though!

**Comment by steven-varga** [comment]
Profiling and runtime attached, done on: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609:  Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz, runtime is near same, slight 1s difference when using std::map 
hope it helps!

![spp runtime](https://user-images.githubusercontent.com/10566766/35059213-6eea5656-fb88-11e7-9deb-b1ed1be8826e.png)
![std unordered runtime](https://user-images.githubusercontent.com/10566766/35059236-7abc543e-fb88-11e7-860b-6b5f471bbd4b.png)
![spp string long](https://user-images.githubusercontent.com/10566766/35059242-7f9d481e-fb88-11e7-9434-d807d8a986aa.png)
![unordered_map string long](https://user-images.githubusercontent.com/10566766/35059248-82c95bd6-fb88-11e7-99fb-eb4a2984151d.png)

**Comment by greg7mdp** [comment]
Hum, I don't know what to say here. The implementation of sparsepp require more copies (or move) of the hash table objects than a regular hash table, so for complex objects which are expensive to copy or move, sparsepp may not be the best alternative.
