### ISSUE TITLE
std::unary_function removed in c++17

### ISSUE THREAD

**Issue by sagaceilo** [greg7mdp/sparsepp#51]
https://github.com/greg7mdp/sparsepp/blob/6bfe3b4bdb364993e612d6bb729d680cf4c77649/sparsepp/spp_utils.h#L198

It seems that unary_function was marked as deprecated in C++11 and removed in C++17 -> http://en.cppreference.com/w/cpp/utility/functional/unary_function. There is a walkaround for that issue mentioned in documentation.

**Comment by Leandros** [comment]
You can simply provide it yourself:

```
template<class ArgumentType, class ResultType>
struct unary_function
{
    typedef ArgumentType argument_type;
    typedef ResultType result_type;
};
```

**Comment by sagaceilo** [comment]
Yup, just found the very same thing a few minutes later. Thanks for
response thou 😉

czw., 1 lut 2018, 07:14 użytkownik Arvid Gerstmann <notifications@github.com>
napisał:

**Comment by greg7mdp** [comment]
Thanks @Leandros and @sagaceilo, I have replaced the use of std::unary_function with a spp class.

**Comment by l33ds** [comment]
Hey friends, could you please release a new official stable version?
I want to have this fixed so I can use C++ 17, so far just working with `master`

**Comment by greg7mdp** [comment]
@l33ds, I just did publish a new release. Thanks for using sparsepp.

**Comment by l33ds** [comment]
So responsive and fast! Thank you :)

**Comment by AraHaan** [comment]
Nice solution but Any solution to the ``std::binary_function`` issue as well?
