### ISSUE TITLE
Can't store mutex inside object

### ISSUE THREAD

**Issue by BotoX** [greg7mdp/sparsepp#53]
The following code snippet produces compile-time errors which are way too big to paste:
```c++
#include <mutex>
#include <unordered_map>
#include <sparsepp/spp.h>
struct z
{
  int val;
  std::mutex mt;
  z(int v) : val(v) {};
};

//std::unordered_map<int, z> miz;
std::sparse_hash_map<int, z> miz;
int main() {
  miz.emplace(
    std::piecewise_construct,
    std::forward_as_tuple(1),
    std::forward_as_tuple(2));
  return 0;
}
```
Works fine with unordered_map, is this possible with this implementation too?

(also try_emplace from C++17 would be cool)

**Comment by greg7mdp** [comment]
Documented in README that values inserted into sparsepp have to either be copyable and movable, or just movable. See example movable.cc.
