### ISSUE TITLE
Move semantics

### ISSUE THREAD

**Issue by im95able** [greg7mdp/sparsepp#54]
If you take o pointer to a value inside the hash table and you do an insert, could that insert invalidate that pointer(not the iterator)? Considering every bucket has a vector and every vector is move aware it probably doesn't invalidate the pointer ?

**Comment by Bu11etmagnet** [comment]
Even if the vector is move-aware, if it has to reallocate, all pointers/iterators/references will be invalidated.

**Comment by greg7mdp** [comment]
Yes, insert can - and will - invalidate pointers to objects stored inside a sparsepp map or set.If that is not acceptable then sparsepp is not a good candidate for your application.
