### ISSUE TITLE
C++ 98 support

### ISSUE THREAD

**Issue by dvysardana** [greg7mdp/sparsepp#55]
Does sparsecpp work with C++98?

Based upon example file hash_std.cc, I created a file called simple.cc in C++98 format and ran it with -std=c++98 option. The code compiles with the following warnings. Is it safe to ignore these warnings?

In file included from simple.cc:3:0:
../sparsepp/spp.h:2315:21: warning: use of C++0x long long integer constant [-Wlong-long]
         if (value < 0xFFFFFFFFULL)        // fits in 4 bytes
                     ^
../sparsepp/spp.h:2338:22: warning: use of C++0x long long integer constant [-Wlong-long]
         if (first4 < 0xFFFFFFFFULL)
                      ^
In file included from ../sparsepp/spp.h:64:0,
                 from simple.cc:3:
../sparsepp/spp_traits.h:55:40: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
     template<> struct is_integral<long long>  : true_type { };
                                        ^
../sparsepp/spp_traits.h:56:49: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
     template<> struct is_integral<unsigned long long> : true_type { };

**Comment by greg7mdp** [comment]
Yes, these are fine to ignore.

**Comment by Bu11etmagnet** [comment]
"long long" support is a common extension in many compilers, even in C++98 mode.
