### ISSUE TITLE
Any recommendations on implementing disk paging on top of this?

### ISSUE THREAD

**Issue by SlowPokeInTexas** [greg7mdp/sparsepp#56]
Greetings, I'm in a position where I will potentially need a structure to store a very large number of hash entries (into the GB). I am investigating sparsepp as a potential candidate with the caveat being I'm interested in adding functionality that will support swapping out pages to disk based on an LRU algorithm. A cursory look at sparsepp docs (I have not thoroughly studied the source) indicates that while sparsepp does support serialization, it appears to support serializing the entire set to a file or stream; it does not appear designed for paging out to disk. 

My questions are, first of all, is it possible?  Secondly, is it recommended? I am open to other alternatives if you have suggestions. I've been a little reluctant to use a more database-oriented solution because I want something that's optimized to use as much memory as possible before resorting to disk.
TIA

**Comment by greg7mdp** [comment]
Yes, there is no partial swapping to disk in sparsepp. In any case that would probably degrade performance a lot. Is there no chance your data would fit into memory in a sparsepp map?

**Comment by SlowPokeInTexas** [comment]
It might, but there are many cases it won't. It is analyzing disk-sectors for duplicated data, so there will be a lot of hashes.

**Comment by greg7mdp** [comment]
Have you thought of using a bloom filter in a first pass?

**Comment by data-man** [comment]
@SlowPokeInTexas 
Try [marisa-trie](https://github.com/s-yata/marisa-trie). This library supports a memory-mapped files.
Maybe it's will be useful for you.

**Comment by SlowPokeInTexas** [comment]
Hi Greg, thank you for your suggestions. I had not considered a bloom filter; I'm looking into it as we speak. As for marisa-trie, that looks pretty interesting. Seems to be geared to strink keys. Thank you for taking the time to make suggestions.
Kindest Regards

**Comment by data-man** [comment]
@SlowPokeInTexas 
I remembered another project: [HArray](https://github.com/Bazist/HArray) (GNU GPL v3.0)
> Serialize/Deserialize from/to file at a speed close to the max speed of the hard drive
