### ISSUE TITLE
Crashing when used on VS 2015

### ISSUE THREAD

**Issue by sirilvk** [greg7mdp/sparsepp#59]
Hi, First of all thanks for this wonderful library. I needed an alternative for std::unordered_map for my application running on windows (its extremely low latency one). So by using sparsepp along with the default allocator it ran fine but didn't get any improvement in performance (of course it took a lot less memory). Then after setting the macro for using sparsepp allocator my application crashed without leaving a core dump (and so unable to point out where). Am using the library as
#define SPP_USE_SPP_ALLOC 1
#include <sparsepp/spp.h>

Please do let me know if i need to set anything more in order to improve the performance and avoid the crash.

Thanks once again,
Siril.

**Comment by greg7mdp** [comment]
Hi Siril, and thank you for the kind words. It is hard to help with performance issue without some kind of test program, so I could see exactly how you use sparsepp. What I have seen is that in some case the hash function is not optimal. You could try defining SPP_MIX_HASH to see if the performance changes.
```
#define SPP_MIX_HASH 1
#include <sparsepp/spp.h>
```
Also you are right the sparsepp allocator could help on windows. Could you provide a small sample program that reproduces the crash?
