### ISSUE TITLE
error during unserializing a sprasehashmap<string,vector<int>>

### ISSUE THREAD

**Issue by RaguRam9967** [greg7mdp/sparsepp#60]
hi i tried to insert values for the map which has string as key and vector of integers as values. after that i dumped the map into the file using,
 FILE *out = fopen("ages.dmp", "wb");
  ages.serialize(FileSerializer(), out);
upto this point everything seems to be fine.
But when i try unserializing it, im getting some error(i think memory issues).
for unserializing i used,
FILE *input = fopen("ages.dmp", "rb");
   readages.unserialize(FileSerializer(), input);
    fclose(input);
Could you please help me with this ?

**Comment by greg7mdp** [comment]
Hi, please provide a small sample of code that reproduces the issue, and I'll look into it.

**Comment by greg7mdp** [comment]
closing because no sample provided... feel free to reopen if needed.
