### ISSUE TITLE
insert and move semantics

### ISSUE THREAD

**Issue by kuviman** [greg7mdp/sparsepp#62]
```c++
std::string s = "abacaba";
spp::sparse_hash_set<std::string> q;
q.insert(s);
assert(s == "abacaba");
```

The assertions fails with `spp::sparse_hash_set`, but works with `std::unordered_set`.

**Comment by greg7mdp** [comment]
@kuviman , very sorry for the delay in fixing this bad issue, and thank you again for reporting it.
