### ISSUE TITLE
Plan for porting into Rust ?

### ISSUE THREAD

**Issue by k3yavi** [greg7mdp/sparsepp#63]
Hi, First of all thanks for the awesome tool! 
I was wondering is there any efforts being made in porting the tool into Rust ?

**Comment by greg7mdp** [comment]
Hi @k3yavi , thanks for the kind words. It would certainly be an interesting project to port sparsepp to Rust, however I am unaware of any such project. I myself don't know Rust and have little time, so it probably would have to be done by someone else.

**Comment by k3yavi** [comment]
Thanks @greg7mdp  for super fast reply.
I myself am in early stage of learning rust too, but my current project requires sparse implementation of hash that's why was curious. My effort for porting your tool is going here https://github.com/k3yavi/sparsers.
I am trying to use the [rust-bindgen](https://github.com/rust-lang-nursery/rust-bindgen) but unfortunately it needed one header. I tried older version of `sparsepp` - `v0.9` which has single header but even that was giving error with bind-gen.
