### ISSUE TITLE
Poor performance for inserting 100000 entries in sparse hash map compared to std::unordered_map

### ISSUE THREAD

**Issue by sirilvk** [greg7mdp/sparsepp#64]
Hi,

Just a simple benchmark program (C++) comparing your sparse hash map with unordered_map got me results were unordered_map performed much better. Would like to check with you on this. Is this expected with the latest g++ libraries? 

Am running on ubuntu 18.04

$ g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

And my program is attached along with this.

The last output is as follows:
$ ./a.out
sparse hash map time 1211270
unordered map time 53430

[testmap.cpp.txt](https://github.com/greg7mdp/sparsepp/files/2013102/testmap.cpp.txt)

Thanks,
Siril.

**Comment by greg7mdp** [comment]
Hi Siril, and thanks for the report. Could you run the test again with strings of the same length just for a fair comparison (we may be hitting the small string optimization in the second case).

**Comment by greg7mdp** [comment]
Also try thie:

`sparse_hash_map<double, std::string, std::hash<double> > shmap(200000);`

now faster than std::unordered_map.

**Comment by greg7mdp** [comment]
I have improved the hashing for doubles in the latest version of sparsepp. Along with the reserve sparsepp is now faster than std::unordered_map.
