### ISSUE TITLE
spp_mix_64 converts uint64_t into size_t

### ISSUE THREAD

**Issue by l33ds** [greg7mdp/sparsepp#65]
Hello,
The following code makes that cast:
https://github.com/greg7mdp/sparsepp/blob/master/sparsepp/spp_utils.h#L198
It's not guaranteed that `size_t` can hold 64 bits, and triggers the following warning:
...sparsepp\sparsepp\spp_utils.h(198): warning C4244: 'return': conversion from 'uint64_t' to 'std::size_t', possible loss of data (compiling source file FunctionCallInterface.cpp)

**Comment by greg7mdp** [comment]
Fixed the warning, thanks for reporting the issue.
