### ISSUE TITLE
cannot serialize and deserialize map<int,vector<string>> in c++

### ISSUE THREAD

**Issue by RaguRam9967** [greg7mdp/sparsepp#67]
when i try to insert values into map<int, vector<string>> and serialize into a .dmp file, there is no error. but when i try to deserialize the .dmp file into a map, it makes some segmentation fault. can you please help me ???

**Comment by RaguRam9967** [comment]
This is the sample code for the above mentioned issue.
//headers included....
#include <sparsepp/spp_timer.h>
#include <sparsepp/spp_memory.h>
#include <sparsepp/spp.h>
using spp::sparse_hash_map;
int main()
{
   sparse_hash_map<int, vector<string>> recMap;
   {
       // here im loading some 2 lakh entries into this map
   }

// here serializing age hash_map to "tempMap.dmp" file    
   FILE *out = fopen("tempMap.dmp", "wb");
   recMap.serialize(FileSerializer(), out);
   fclose(out);
   recMap.clear(); //cleared the map
   //it doesnt raised any errors till this.
   
   //now im tryting to read read from "tempMap.dmp" file into recMap
   FILE *input = fopen("tempMap.dmp", "rb");
   recMap.unserialize(FileSerializer(), input);
   fclose(input);
//here when i try to deserialize the file into a map, it throws some segmentation fault.
}
PS: when i use this syntax, map<int, string> it works fine, but the issue araised when i used vector<string> in place of string. And i have used your FileSerializer class in the code (for serialize/deserialize).
Thank you.
Please help me to resolve the issue....

**Comment by greg7mdp** [comment]
Hi there, please provide a full sample reproducing the issue. You can create a gist if you want (at https://gist.github.com/).

**Comment by greg7mdp** [comment]
You are missing the serialization functions for std::vector. Try adding this in FileSerializer:

```
    // serialize std::vector<T> to FILE
    // --------------------------------
    template <class T>
    bool operator()(FILE *fp, const std::vector<T>& value)
    {
        const size_t size = value.size();
        if (!(*this)(fp, size))
            return false;
        for (size_t i=0; i<size; ++i)
            if (!(*this)(fp, value[i]))
                return false;
        return true;
    }

    template <class T>
    bool operator()(FILE *fp, std::vector<T>* value)
    {
        size_t size;
        if (!(*this)(fp, &size))
            return false;
        new (value) std::vector<T>(size);
        for (size_t i=0; i<size; ++i)
            if (!(*this)(fp, &(*value)[i]))
                return false;
        return true;
    }
```

**Comment by RaguRam9967** [comment]
Hi @greg7mdp , it is working. thanks a lot for your quick response. 

and i have another question, if i want to use map<int , map<string, vector<int>>> what changes should i make ?

**Comment by greg7mdp** [comment]
I don't see the difference between the two, but I believe the answer is yes it will work for both.

**Comment by RaguRam9967** [comment]
okay @greg7mdp, sure. got it. Thanks a lot for your fast response and your valuable time to make this clear.
Thank you once again! you are awesome.  Cheers !!!

**Comment by greg7mdp** [comment]
You are welcome. Closing the issue but you are welcome to reopen if needed. Thanks.

**Comment by RaguRam9967** [comment]
hi @greg7mdp there is some issues when i used that code of yours for     
map<int, map<string, vector<int>>>. Check you please check that ????
Thanks.
these are the errors it displayed : (im running in a ubuntu 64bit machine and compiling from terminal)

temp3.cpp:174:25: error: ‘spp_hash’ does not name a type
               class H = spp_hash<K>, 
                         ^
temp3.cpp:174:33: error: expected ‘>’ before ‘<’ token
               class H = spp_hash<K>, 
                                 ^
temp3.cpp:177:67: error: ‘E’ was not declared in this scope
     bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
                                                                   ^
temp3.cpp:177:70: error: ‘A’ was not declared in this scope
     bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
                                                                      ^
temp3.cpp:177:71: error: template argument 4 is invalid
     bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
                                                                       ^
temp3.cpp:177:71: error: template argument 5 is invalid
temp3.cpp:183:25: error: ‘spp_hash’ does not name a type
               class H = spp_hash<K>, 
                         ^
temp3.cpp:183:33: error: expected ‘>’ before ‘<’ token
               class H = spp_hash<K>, 
                                 ^
temp3.cpp:186:61: error: ‘E’ was not declared in this scope
     bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
                                                             ^
temp3.cpp:186:64: error: ‘A’ was not declared in this scope
     bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
                                                                ^
temp3.cpp:186:65: error: template argument 4 is invalid
     bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
                                                                 ^
temp3.cpp:186:65: error: template argument 5 is invalid
temp3.cpp: In member function ‘bool FileSerializer::operator()(FILE*, const int&)’:
temp3.cpp:179:57: error: ‘E’ was not declared in this scope
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                         ^
temp3.cpp:179:60: error: ‘A’ was not declared in this scope
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                            ^
temp3.cpp:179:61: error: template argument 4 is invalid
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                             ^
temp3.cpp:179:61: error: template argument 5 is invalid
temp3.cpp:179:63: error: expected ‘>’ before ‘&’ token
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                               ^
temp3.cpp:179:63: error: expected ‘(’ before ‘&’ token
temp3.cpp:179:64: error: expected primary-expression before ‘>’ token
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                                ^
temp3.cpp:179:73: error: request for member ‘serialize’ in ‘value’, which is of non-class type ‘const int’
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                                         ^
temp3.cpp:179:93: error: expected ‘)’ before ‘;’ token
         return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
                                                                                             ^
temp3.cpp: In member function ‘bool FileSerializer::operator()(FILE*, int*)’:
temp3.cpp:188:51: error: ‘E’ was not declared in this scope
         new (value) spp::sparse_hash_map<K, V, H, E, A>();
                                                   ^
temp3.cpp:188:54: error: ‘A’ was not declared in this scope
         new (value) spp::sparse_hash_map<K, V, H, E, A>();
                                                      ^
temp3.cpp:188:55: error: template argument 4 is invalid
         new (value) spp::sparse_hash_map<K, V, H, E, A>();
                                                       ^
temp3.cpp:188:55: error: template argument 5 is invalid
temp3.cpp:189:23: error: request for member ‘unserialize’ in ‘value->’, which is of non-class type ‘int’
         return value->unserialize(*this, fp);

**Comment by greg7mdp** [comment]
Did you include the sparsepp headers <sparsepp/spp.h>?

**Comment by RaguRam9967** [comment]
yes,i did.

**Comment by greg7mdp** [comment]
try this:

```
    // serialize spp::sparse_hash_map<K, V, H, E, A> to FILE
    // -----------------------------------------------------
    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
    bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
    {
        return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
    }

    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
    bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
    {
        new (value) spp::sparse_hash_map<K, V, H, E, A>();
        return value->unserialize(*this, fp);
    }
```

**Comment by RaguRam9967** [comment]
hi i tried that, but still have few issues,
PS: IM TRYING TO SERIALIZE  'sparse_hash_map<int,sparse_hash_map< string, vector<int>>> '
temp5.cpp:152:66: error: ‘T’ was not declared in this scope
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
                                                                  ^
temp5.cpp:152:67: error: template argument 2 is invalid
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
                                                                   ^
temp5.cpp:152:69: error: template argument 1 is invalid
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
                                                                     ^
temp5.cpp:161:66: error: ‘T’ was not declared in this scope
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
                                                                  ^
temp5.cpp:161:67: error: template argument 2 is invalid
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >
                                                                   ^
temp5.cpp:161:69: error: template argument 1 is invalid
               class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, T> > >

**Comment by greg7mdp** [comment]
My mistake... try this:

```
    // serialize spp::sparse_hash_map<K, V, H, E, A> to FILE
    // -----------------------------------------------------
    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, V> > >
    bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
    {
        return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
    }

    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, V> > >
    bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
    {
        new (value) spp::sparse_hash_map<K, V, H, E, A>();
        return value->unserialize(*this, fp);
    }
```

**Comment by RaguRam9967** [comment]
yupp... its working. thanks a lot for helping me. Thank you again.

**Comment by RaguRam9967** [comment]
hey it seems the code you sent for map<int,vector<string>> is not working properly. for some few entries it is fine i guess but i when  i try to put more entries then while deserializing i could see the values is not inserted properly. can you please check it.
