### ISSUE TITLE
how to find the memory consumed by a specific sparse_hash_map<int,string> or something??

### ISSUE THREAD

**Issue by RaguRam9967** [greg7mdp/sparsepp#68]
im using many maps in my projects like 'sparse_hash_map<int,vector<string>>' and 'sparse_hash_map<int,sparse_hash_map<string, vector<int>>>' so is there a way to get the memory consumed by each map specifically ?

**Comment by greg7mdp** [comment]
No, currently there is no way to get the memory consumed by each map specifically.
Do your maps have a lot of entries in each of them?

**Comment by RaguRam9967** [comment]
well, it depends. actually im trying to insert entries into the map from a large csv file (say more than 2 gb). but obviously i cant load everything. so if i could find the memory consumed by a  map, after some limit i can serialize the map into a file and clear the map so that i can continue inserting the remaining data into it.

**Comment by greg7mdp** [comment]
I think you should figure out if you have many very small maps (just by calling size()) to get the number of elements).

If that is the case you can use my [sho](https://github.com/greg7mdp/sho) header to save memory.

**Comment by RaguRam9967** [comment]
yea i know how to get the size of the map. but i need to know the memory consumed by a map.

**Comment by greg7mdp** [comment]
Map size cannot be computed reliable, as we don't know the allocator overhead when allocating small buffers. It would be better to track the process memory usage to decide when it is appropriate to serialize to disk.
