### ISSUE TITLE
serialize / deserialize sparse_hash_map<int, sparse_hash_map <int , string> >

### ISSUE THREAD

**Issue by Ragu9967** [greg7mdp/sparsepp#69]
Hi @greg7mdp, how to serialize/deserialize containers like 'sparse_hash_map<int, sparse_hash_map <int , string> >' i tried with that updated File Serializer class where you added code for handling the <int , vector < string >> types but it seems that there is some issues with it as i couldnt get a proper output.
It would be great if you could help me with this.
Thanks.

**Comment by greg7mdp** [comment]
Please send me a full program I can use for testing, and I'll look into it. Thanks - greg

**Comment by greg7mdp** [comment]
@Ragu9967 , closing issue as sample program not submitted. Please reopen if you want to provide one.
