### ISSUE TITLE
Support operator[] with rvalue

### ISSUE THREAD

**Issue by philippecp** [greg7mdp/sparsepp#73]
The following code doesn't compile:

#include "sparsepp/spp.h"
#include <unordered_map>

using namespace std;

int main()
{
	using Key = std::unique_ptr<std::string>;
	using Value = std::unique_ptr<std::string>;
#if 1
	using AssociativeContainer = spp::sparse_hash_map<Key, Value>;
#else
	using AssociativeContainer = unordered_map<Key, Value>;
#endif
	AssociativeContainer c;
	auto& value = c[std::make_unique<std::string>("other_key")];
}

**Comment by greg7mdp** [comment]
Hi Philippe, thanks for reporting this issue. I fixed the insertion of rvalues... however maybe some other APIs will have difficulty with those. If that is the case please let me know and I will try to address the issue quickly. I have added an example in sparsepp/examples: insert_rvalue.cc.
