### ISSUE TITLE
When hashing on vector

### ISSUE THREAD

**Issue by KeithYue** [greg7mdp/sparsepp#74]
I want to store unique vector<int>, so I use spp::sprase_hash_set<vector<int>>, here is my hash function for vector:
`
// code
namespace std{

     template<>

     struct hash<vector<int>>{
         std::size_t operator()(std::vector<int> const& vec) const {
           std::size_t seed = vec.size();
           for(auto& i : vec) {
             seed ^= i + 0x9e3779b9 + (seed << 6) + (seed >> 2);
           }
           return seed;
         }
     };
 }

`

Here is my test function:
`
void test_hash(){
     std::vector<int> a = {2,3,4};
     std::vector<int> b = {4,5,6};
     std::vector<int> c = {2,3,4};
     std::vector<int> d = {1,2,3};

     spp::sparse_hash_set<std::vector<int>> s;
     std::unordered_set<vector<int>> u;

     s.insert(a);
     s.insert(b);

     u.insert(a);
     u.insert(b);

     if(s.find(a) != s.end()){
         cout << "s has a" << endl;
     }
     if(u.find(a) != u.end()){
         cout << "u has a" << endl;
     }

 }`

Here is the output:
`u has a`

So the unordered_map can output the correct answer, but sparse_hash_set cannot.
What's the problem? By the way, I really enjoy the efficiency of sparse_hash_set.

**Comment by greg7mdp** [comment]
Hum, it doesn't look like the code you sent would compile. For example you use `std::vector a = {2,3,4};` instead of `std::vector<int> a = {2,3,4};`.

Can you post the exact test program you used?

Thanks!

**Comment by KeithYue** [comment]
`s.contains(c)` should be `true`, since the vectors `a` and `c` is the same.

**Comment by KeithYue** [comment]
> Thanks. I'm travelling now so I may not be able to look at this right away, but I'll investigate it.
> In your test `s.contains(c)` should be false, right?

`s.contains(c) should be true, since the vectors` a `and `c` is the same.

**Comment by KeithYue** [comment]
Here is the output of the test program.
![screen shot 2018-12-06 at 2 43 57 pm](https://user-images.githubusercontent.com/1284810/49566410-7719e900-f965-11e8-83c8-37a7dde5235f.png)

**Comment by greg7mdp** [comment]
What compiler are you using? I just tried it with gcc 5.4.0 and got the expected output:
![image](https://user-images.githubusercontent.com/1496907/50428470-0855ee80-0886-11e9-9db5-0e0089005946.png)

**Comment by KeithYue** [comment]
I am using gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by KeithYue** [comment]
> What compiler are you using? I just tried it with gcc 5.4.0 and Visual Studio 2017, and got the expected output with both:
> ![image](https://user-images.githubusercontent.com/1496907/50428470-0855ee80-0886-11e9-9db5-0e0089005946.png)

I am using gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by KeithYue** [comment]
> OK, are you really sure that the issue you are reporting is real?
> I just tried with gcc 7.4 on ubuntu-trusty-64, and again got the expected output:
> ![image](https://user-images.githubusercontent.com/1496907/50449976-c4e89800-08f8-11e9-8cf6-1e2fc553bc07.png)

I am using C++14， maybe this

**Comment by KeithYue** [comment]
I have tried, I can not get the write answer. Here is the source code (main.cpp).
```
 #include <sparsepp/spp.h>
 #include <vector>
 #include <iostream>
 #include <unordered_set>

 using namespace std;
 // hash function for vector
 namespace std{
      template<>
      struct hash<vector<int>>{
          std::size_t operator()(std::vector<int> const& vec) const {
            std::size_t seed = vec.size();
            for(auto& i : vec) {
              seed ^= i + 0x9e3779b9 + (seed << 6) + (seed >> 2);
            }
            return seed;
          }
      };
  }

 void test_hash(){
      std::vector<int> a = {2,3,4};
      std::vector<int> b = {4,5,6};
      std::vector<int> c = {2,3,4};
      std::vector<int> d = {1,2,3};

      spp::sparse_hash_set<std::vector<int>> s;
      std::unordered_set<vector<int>> u;

      s.insert(a);
      s.insert(b);

      u.insert(a);
      u.insert(b);


      if(s.find(a) != s.end()){
          cout << "s has a" << endl;
      }
      if(u.find(a) != u.end()){
          cout << "u has a" << endl;
      }
      cout << s.contains(a) << endl; // should be 1
      cout << s.contains(c) << endl; // should be 1
      cout << s.contains(d) << endl; // should be 0

  }


 int main(){
     test_hash();
 }

```
Here is the compile command: 
`g++ -std=c++11 main.cpp -o test -I ./`

Here is the output:

![screen shot 2018-12-27 at 11 17 06 am](https://user-images.githubusercontent.com/1284810/50463884-0b0d2c80-09c9-11e9-932e-67ac2756aeaa.png)

**Comment by greg7mdp** [comment]
I built your exact program and cannot reproduce the issue. Are you using the latest version of sparsepp?

**Comment by greg7mdp** [comment]
also, please provide the output of the command: `g++ -v`

**Comment by KeithYue** [comment]
Finally it works after I update spp to the latest version. Thanks very much.

**Comment by greg7mdp** [comment]
Great, Thanks!
