### ISSUE TITLE
Help me to serialize/deserialize sparse_hash_map<int , vector< std::string > > 

### ISSUE THREAD

**Issue by Ragu9967** [greg7mdp/sparsepp#75]
#include <cstdio>
#include <stdlib.h>
#include <algorithm>
#include <vector>
#include <fstream>
#include <sparsepp/spp_timer.h>
#include <sparsepp/spp_memory.h>
#include <sparsepp/spp.h>
//PLEASE USE THIS SPARSEPP LIBRAR. I HAVENT INCLUDED IT
using spp::sparse_hash_map;
using namespace std;

class FileSerializer
{
public:
    // serialize basic types to FILE
    // -----------------------------
    template <class T>
    bool operator()(FILE *fp, const T& value)
    {
        return fwrite((const void *)&value, sizeof(value), 1, fp) == 1;
    }

    template <class T>
    bool operator()(FILE *fp, T* value)
    {
        return fread((void *)value, sizeof(*value), 1, fp) == 1;
    }

    // serialize std::string to FILE
    // -----------------------------
    bool operator()(FILE *fp, const string& value)
    {
        const size_t size = value.size();
        return (*this)(fp, size) && fwrite(value.c_str(), size, 1, fp) == 1;
    }

    bool operator()(FILE *fp, string* value)
    {
        size_t size;
        if (!(*this)(fp, &size))
            return false;
        char* buf = new char[size];
        if (fread(buf, size, 1, fp) != 1)
        {
            delete [] buf;
            return false;
        }
        new (value) string(buf, (size_t)size);
        delete[] buf;
        return true;
    }

    // serialize std::pair<const A, B> to FILE - needed for maps
    // ---------------------------------------------------------
    template <class A, class B>
    bool operator()(FILE *fp, const std::pair<const A, B>& value)
    {
        return (*this)(fp, value.first) && (*this)(fp, value.second);
    }

    template <class A, class B>
    bool operator()(FILE *fp, std::pair<const A, B> *value)
    {
        return (*this)(fp, (A *)&value->first) && (*this)(fp, &value->second);
    }
};

float _to_gb(uint64_t m) { return (float)((double)m / (1024 * 1024 * 1024)); }
//HERE IM JUST TRYING TO SERIALIZE AND DESERIALIZE A STL MAP of this syntax : map<int,vector<std::string>>
int main(int, char* [])
{
    sparse_hash_map<int, vector<std::string>> spMap;

    //adding some sample entries
    vector<string> temp={"hey","there","solve","this","error"};
    
    for(int i=0 ; i < 10000 ; i++)
         spMap[i]=temp;
    
    //serialize age hash_map to "tempMap.dmp" file
    FILE *out = fopen("tempMap.dmp", "wb");
    spMap.serialize(FileSerializer(), out);
    fclose(out);

    spMap.clear();
   
    // read from "tempMap.dmp" file into age_read hash_map
    FILE *input = fopen("tempMap.dmp", "rb");
    spMap.unserialize(FileSerializer(), input);
    fclose(input);
    printf("after unserialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
    
}

**Comment by greg7mdp** [comment]
There is an example in the examples directory which has the FileSerializer you need.

However I have updated your example so that it works:

```c++
#include <stdlib.h>
#include <sparsepp/spp_timer.h>
#include <sparsepp/spp_memory.h>
#include <sparsepp/spp.h>
#include <vector>
#include <string>
#include <iostream>

using spp::sparse_hash_map;
using namespace std;

class FileSerializer
{
public:
    // serialize basic types to FILE
    // -----------------------------
    template <class T>
    bool operator()(FILE *fp, const T& value)
    {
        return fwrite((const void *)&value, sizeof(value), 1, fp) == 1;
    }

    template <class T>
    bool operator()(FILE *fp, T* value)
    {
        return fread((void *)value, sizeof(*value), 1, fp) == 1;
    }

    // serialize std::string to FILE
    // -----------------------------
    bool operator()(FILE *fp, const string& value)
    {
        const size_t size = value.size();
        return (*this)(fp, size) && fwrite(value.c_str(), size, 1, fp) == 1;
    }

    bool operator()(FILE *fp, string* value)
    {
        size_t size;
        if (!(*this)(fp, &size))
            return false;
        char* buf = new char[size];
        if (fread(buf, size, 1, fp) != 1)
        {
            delete [] buf;
            return false;
        }
        new (value) string(buf, (size_t)size);
        delete[] buf;
        return true;
    }

    // serialize std::vector<T, A> to FILE
    // -----------------------------------
    template <class T, class A = std::allocator<T>>
    bool operator()(FILE *fp, const std::vector<T, A>& value)
    {
        const size_t size = value.size();
        if (!(*this)(fp, size))
            return false;
        for (size_t i=0; i<size; ++i)
            if (!(*this)(fp, value[i]))
                return false;
        return true;
    }

    template <class T, class A = std::allocator<T>>
    bool operator()(FILE *fp, std::vector<T, A>* value)
    {
        size_t size;
        if (!(*this)(fp, &size))
            return false;
        new (value) std::vector<T, A>(size);
        for (size_t i=0; i<size; ++i)
            if (!(*this)(fp, &(*value)[i]))
                return false;
        return true;
    }

    // serialize spp::sparse_hash_map<K, V, H, E, A> to FILE
    // -----------------------------------------------------
    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, V> > >
    bool operator()(FILE *fp, const spp::sparse_hash_map<K, V, H, E, A>& value)
    {
        return const_cast<spp::sparse_hash_map<K, V, H, E, A> &>(value).serialize(*this, fp);
    }

    template <class K, class V, 
              class H = spp::spp_hash<K>, 
              class E = std::equal_to<K>, 
              class A = SPP_DEFAULT_ALLOCATOR<std::pair<const K, V> > >
    bool operator()(FILE *fp, spp::sparse_hash_map<K, V, H, E, A> *value)
    {
        new (value) spp::sparse_hash_map<K, V, H, E, A>();
        return value->unserialize(*this, fp);
    }

    // serialize std::pair<const A, B> to FILE - needed for maps
    // ---------------------------------------------------------
    template <class A, class B>
    bool operator()(FILE *fp, const std::pair<const A, B>& value)
    {
        return (*this)(fp, value.first) && (*this)(fp, value.second);
    }

    template <class A, class B>
    bool operator()(FILE *fp, std::pair<const A, B> *value)
    {
        return (*this)(fp, (A *)&value->first) && (*this)(fp, &value->second);
    }
};

float _to_gb(uint64_t m) { return (float)((double)m / (1024 * 1024 * 1024)); }

//HERE IM JUST TRYING TO SERIALIZE AND DESERIALIZE A STL MAP of this syntax : map<int,vector<std::string>>
int main(int, char* [])
{
    sparse_hash_map<int, vector<std::string>> spMap;

    //adding some sample entries
    vector<string> temp={"hey","there","solve","this","error"};

    for(int i=0 ; i < 10000 ; i++)
        spMap[i] = temp;

    //serialize age hash_map to "tempMap.dmp" file
    FILE *out = fopen("tempMap.dmp", "wb");
    spMap.serialize(FileSerializer(), out);
    fclose(out);

    spMap.clear();

    // read from "tempMap.dmp" file into age_read hash_map
    FILE *input = fopen("tempMap.dmp", "rb");
    spMap.unserialize(FileSerializer(), input);
    fclose(input);

    cout << "spMap size is " << spMap.size() << " -> " << spMap.contains(22) << endl;
    printf("after unserialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
}
```
