### ISSUE TITLE
missing return value in function spp_sptr& operator=(spp_sptr &&o) ?

### ISSUE THREAD

**Issue by fangpin** [greg7mdp/sparsepp#76]
Why there is no return in function spp_smartptr.h/spp_sptr& operator=(spp_sptr &&o), 
[spp_sptr& operator=(spp_sptr &&o)
    {
        if (_p) _p->decrement(); 
        _p = o._p;
        o._p = (T *)0; 
    }](url)
```cpp
spp_sptr& operator=(spp_sptr &&o)
    {
        if (_p) _p->decrement(); 
        _p = o._p;
        o._p = (T *)0; 
    }
```
Should return *this?

**Comment by greg7mdp** [comment]
Yes, you are right, thanks you for reporting this mistake. I have just checked in the fix.
