### ISSUE TITLE
SIGSEGV on using move-assigned-from hash set

### ISSUE THREAD

**Issue by Marukyu** [greg7mdp/sparsepp#77]
Moving a `spp::sparse_hash_set` causes the moved-from instance to enter an invalid state with a `bucket_count` of 0, resulting in undefined behavior when performing an operation such as `erase()`, as most of the sparsepp library assumes a non-zero `bucket_count`. Clearing the affected hash set after moving does not appear to fix the invalid `bucket_count`.

`std::unordered_set` does not exhibit the same issue (at least on GCC); the C++ standard guarantees that the container is left in an unspecified, but valid state after being moved.

If this difference from the standard library containers is intended, it might be helpful to add it to the 'Warning' section in the repository's `README.md` file.

The issue can be reproduced with the following code snippet, which crashes when compiled with GCC on Linux:

```cpp
#include <sparsepp/spp.h>
#include <utility>

int main()
{
	spp::sparse_hash_set<int> test1;
	spp::sparse_hash_set<int> test2 = std::move(test1);
	test1.clear();
	test1.erase(0);
}
```

**Comment by greg7mdp** [comment]
@Marukyu, thank you very much for reporting the issue, and I do appreciate you providing the small program to reproduce it. I just checked in a fix. Please let me know if you have any further problem with sparsepp.

**Comment by Marukyu** [comment]
@greg7mdp, thank you so much for the fast response and fix! After updating to the latest version, sparsepp now works perfectly within my project. I especially appreciate the library's built-in support for efficient table serialization/deserialization.

**Comment by greg7mdp** [comment]
@Marukyu, I'm delighted that sparsepp works well for you. Thanks for letting me know.
