### ISSUE TITLE
Lookup non-present keys becomes very slow.

### ISSUE THREAD

**Issue by lizkwan** [greg7mdp/sparsepp#80]
"For basic integer types, sparsepp provides a default hash function which does some mixing of the bits of the keys (see Integer Hashing). This prevents a pathological case where inserted keys are sequential (1, 2, 3, 4, ...), and the lookup on non-present keys becomes very slow."

I've run to the problem you mentioned in the documentation.
I have a hash map (sparse_hash_map<int64_t, string>), then I insert ~10million of data with ascending integer keys from 1 to n. 

When lookup for non-present keys, it get slower the more I lookup.
I know that you address the fix for this (https://github.com/greg7mdp/sparsepp/issues/21).
May I know the underlying reason why it's slower for non-present keys and mixing bits of keys solve the problem? Any reference for this are greatly appreciate.

**Comment by greg7mdp** [comment]
This is because we know that a key is not present when we find an empty spot. This takes a long time when many contiguous spots are occupied, because we resolve collisions with probing neighboring locations (see https://en.wikipedia.org/wiki/Open_addressing - we use quadratic probing).
