### ISSUE TITLE
Do you support C++11 stateful allocators?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [greg7mdp/sparsepp#81]
Does sparsepp ever make its own clean instance of my custom Allocator and allocates from that instead of a copy of the allocator I passed in the constructor?

**Comment by greg7mdp** [comment]
> Does sparsepp ever make its own clean instance of my custom Allocator and allocates from that instead of a copy of the allocator I passed in the constructor?

I don't believe so, although the support of stateful allocators in sparsepp is probably not 100% correct. If you want to use stateful allocators I recommend you use https://github.com/greg7mdp/parallel-hashmap
