### ISSUE TITLE
memcpy can happen with null "source" parameter

### ISSUE THREAD

**Issue by brenoguim** [greg7mdp/sparsepp#86]
In the following line:
https://github.com/greg7mdp/sparsepp/blob/209cb772c28272eb6b2157b79afe554c0102fb61/sparsepp/spp.h#L2090

`memcpy` can happen with `_first_group` as a null pointer and count `0`. Passing null to the second argument is an undefined behavior, even if count is zero.

**Comment by greg7mdp** [comment]
> Passing null to the second argument is an undefined behavior, even if count is zero.

What is the source for this statement? Just curious.

**Comment by brenoguim** [comment]
https://en.cppreference.com/w/cpp/string/byte/memcpy
> If either dest or src is a null pointer, the behavior is undefined, even if count is zero.

**Comment by greg7mdp** [comment]
fair enough. I'll check in a fix

**Comment by greg7mdp** [comment]
This ought to do it.

**Comment by brenoguim** [comment]
Thanks!!

**Comment by greg7mdp** [comment]
@brenoguim my previous fix was wrong, I updated it. Thanks - greg
