### ISSUE TITLE
Problem when compiling on macOS catalina 

### ISSUE THREAD

**Issue by AneesHl** [greg7mdp/sparsepp#88]
Hi, I'm trying to build a project on macOS Catalina that contains sparsepp but I'm getting a fatal error (similar to an old closed issue). I'm not sure what the cause of the issue is:

=====

discodop/../sparsepp/sparsepp/spp_utils.h:87:17: fatal error: 'tr1/functional' file not found
       #include <tr1/functional>
                ^~~~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

=====

Any hint/help is much appreciated. Thanks

**Comment by greg7mdp** [comment]
Try just replacing the line:
`    #if __has_feature(cxx_noexcept)  // what to use here?`
with
`    #if 1`

the issue is that sparsepp supports really old compilers.

**Comment by AneesHl** [comment]
thank you!

**Comment by andreasvc** [comment]
Wouldn't it be good to fix this issue properly so that both old and new compilers are supported? i.e., replace `#if __has_feature(cxx_noexcept)` with another condition?

**Comment by greg7mdp** [comment]
Yes, it would be great but I don't have access to macs with various xcode versions to check what works and what not.

**Comment by andreasvc** [comment]
Fair enough, same here. A workaround would be to check not just `__has_feature(cxx_noexcept)` but also a user-supplied/user-overridable define, such as `SPP_CXX11`.

**Comment by greg7mdp** [comment]
Excellent suggestion, thanks @andreasvc, done.
