### ISSUE TITLE
unexpected memory usage after unserialization

### ISSUE THREAD

**Issue by zhaoyanswill** [greg7mdp/sparsepp#9]
Hi,

sparsepp is really great!

I create a <uint64_t, string> map. In my test code, about 178M <uint64_t,string> pairs are inserted into the map. And then I look-up them again. While looking up them, the memory usage is ~4.995G.

And then I add serialization and unserialization code (copied from your example 3) between insertion and look-up part. During the serialization, the memory usage is still ~4.995G. However, after unserialization, the memory usage is ~12.024G. The serialized file is ~4.4G.

Do you have any idea about this? My computing scenario is building map once and looking-up many times. Thank you!

**Comment by greg7mdp** [comment]
Hi,

Thank you for the kind words!

Let's try to figure out what happens. In the example, I do unserialize into a second hash_map, so the memory would be doubled. Do you do the same thing?

If yes, you could put braces around the lines using the first hash map, so the memory used by the first hash map would be released when exiting the block, such as:

```int main(int argc, char* argv[]) 
{
    {
         sparse_hash_map<string, int> age{ { "John", 12 }, {"Jane", 13 }, { "Fred", 8 } };

        // serialize age hash_map to "ages.dmp" file
        FILE *out = fopen("ages.dmp", "wb");
        age.serialize(FileSerializer(), out);
        fclose(out);
    }
    ...
```

**Comment by zhaoyanswill** [comment]
Thank you for your reply! I used one map. The code is shown below:

	FILE *out = fopen("uniq.map", "wb");
	mUniq.serialize(FileSerializer(), out);
	fclose(out);
	mUniq.clear();
	cout << "clean:\t" << mUniq.size() << endl;

	// look up
	FILE *input = fopen("uniq.map", "rb");
	mUniq.unserialize(FileSerializer(), input);
	fclose(input);

**Comment by greg7mdp** [comment]
OK, thank. Let me have a look at this and I'll get back to you.

**Comment by zhaoyanswill** [comment]
Thanks a lot!

**Comment by greg7mdp** [comment]
What is the type of mUniq?

**Comment by zhaoyanswill** [comment]
spp::sparse_hash_map<uint64_t, string> mUniq;

Thanks!

**Comment by greg7mdp** [comment]
Please share your full test program. Here is the one I used, and I don't see any abnormal memory usage:

```
    sparse_hash_map<string, int> age;

    for (size_t i=0; i<100000000; ++i)
    {
        char buff[20];
        sprintf(buff, "%lld", i);
        age.insert(std::make_pair(std::string(buff), i));
    }

    printf("before serialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
    // serialize age hash_map to "ages.dmp" file
    FILE *out = fopen("ages.dmp", "wb");
    age.serialize(FileSerializer(), out);
    fclose(out);

    printf("before clear(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
    age.clear();
    printf("after clear(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
    

    // read from "ages.dmp" file into age_read hash_map 
    FILE *input = fopen("ages.dmp", "rb");
    age.unserialize(FileSerializer(), input);
    fclose(input);
    printf("after unserialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
```

and the output:

```
before serialize(): mem_usage  6.3 GB
before clear(): mem_usage  6.3 GB
after clear(): mem_usage  0.0 GB
after unserialize(): mem_usage  4.4 GB
```

**Comment by zhaoyanswill** [comment]
Here is my code. Another question: I tried to used your app::GetProcessMemoryUsed() but didn’t work.  Thanks!

int main(int argc, char** argv)
{
	vector<string> vTest;
	size_t nNum = 1e7;
	{
		string sUnique = "unique";
		ifstream iffU(sUnique);
		string sSeqU;
		getline(iffU, sSeqU);
		iffU.close();

		vector<string> vSplit;
		split(vSplit, sSeqU, is_any_of("|"));
		cout << "total size:\t" << vSplit.size() << endl;

		vTest.assign(vSplit.begin(), vSplit.begin()+nNum);
	}
	cout << "testing size:\t" << vTest.size() << endl;

	uint32_t aC2I[128];
	fill_n(aC2I, 128, 9);
	aC2I['A'] = 0;
	aC2I['C'] = 1;
	aC2I['G'] = 2;
	aC2I['T'] = 3;
	char aI2C[4] = {'A', 'C', 'G', 'T'};

	//dense_hash_map<uint64_t, string> mUniq;
	//mUniq.set_empty_key(0);
	spp::sparse_hash_map<uint64_t, string> mUniq;
	//unordered_map<uint64_t, string> mUniq;

	// insert
	auto t1 = TClock::now();
	string sRs;
	size_t nInsert = 0;
	size_t nN = 0;
	for (size_t i = 0; i < vTest.size(); ++i)
	{
		if (vTest[i][0]=='r')
		{
			sRs = vTest[i];
			continue;
		}
		for (size_t j = 0; j < vTest[i].size()-27+1; ++j)
		{
			uint64_t nNum = mer2num(vTest[i], j, 27, aC2I);
			string s = num2mer(nNum, 27, aI2C);
			assert (s == vTest[i].substr(j,27));

			auto it = mUniq.find(nNum);
			if (it != mUniq.end())
				it->second += '|'+sRs;
			else
				mUniq[nNum] = sRs;
			++nInsert;
		}
	}
	cout << "insert done:\t" << duration_cast<seconds>(TClock::now()-t1).count() << endl;
	printf("before serialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));

	FILE *out = fopen("uniq.map", "wb");
	mUniq.serialize(FileSerializer(), out);
	fclose(out);
	printf("before clear(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
	mUniq.clear();
	printf("after clear(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));
	cout << "clean:\t" << mUniq.size() << endl;

	// look up
	FILE *input = fopen("uniq.map", "rb");
	mUniq.unserialize(FileSerializer(), input);
	fclose(input);
	printf("after unserialize(): mem_usage %4.1f GB\n",  _to_gb(spp::GetProcessMemoryUsed()));

	t1 = TClock::now();
	size_t nMatch = 0;
	sRs = "";
	for (size_t i = 0; i < vTest.size(); ++i)
	{
		if (vTest[i][0]=='r')
		{
			sRs = vTest[i];
			continue;
		}
		for (size_t j = 0; j < vTest[i].size()-27+1; ++j)
		{

			uint64_t nNum = mer2num(vTest[i], j, 27, aC2I);
			string s = num2mer(nNum, 27, aI2C);
			assert (s == vTest[i].substr(j,27));

			if (mUniq[nNum].find(sRs) != string::npos) ++nMatch;
		}
	}
	cout << "look-up done:\t" << duration_cast<seconds>(TClock::now()-t1).count() << endl;

	cout << mUniq.size() << endl;
	cout << nMatch << endl;
	cout << nInsert << endl;

	return 0;
}

**Comment by greg7mdp** [comment]
Thanks. Please also provide the source code for the functions mer2num and num2mer.

**Comment by zhaoyanswill** [comment]
Here is the code. 

uint64_t mer2num(string& s, uint32_t nOff, uint32_t nK, const uint32_t* aC2I)
{
	uint64_t nNum = 0;
	for (size_t i = nOff; i < nOff+nK; ++i)
	{
		nNum = (nNum<<2) | aC2I[s[i]];
	}
	return nNum;
}

string num2mer(uint64_t nNum, uint32_t nK, const char* aI2C)
{
	string s;
	s.reserve(nK);
	for (int i = (nK-1)*2; i>=0; i-=2)
	{
		s += aI2C[(nNum>>i)&3];
	}
	return s;
}

**Comment by greg7mdp** [comment]
OK, now your example builds, but it doesn't fill the hash_map with data. Probably because I don't have the "unique" file.

**Comment by zhaoyanswill** [comment]
The “unique” file is huge. It consists of “r[0-9]|seq1|seq2|seq3|seq4”. Each seq consists of A,C,G,T. You may randomly generate some or I can write a python script that is able to generate some. Thanks for your time!

**Comment by greg7mdp** [comment]
Yes, please provide the python script, or some C++ code that adds the sequences to the sparse_hash_map rather than reading them from a file.

**Comment by zhaoyanswill** [comment]
It’s weird that memory usage is normal while I insert either 1e8 random uint64_t numbers and their index or [(ULLONG_MAX-0,0), (ULLONG_MAX-1e8,1e8)) and serialize/unserialize the map. I’ll check my previous code. Thank you for your help!

**Comment by zhaoyanswill** [comment]
Hi, I finally figured out what I really wanted to ask about!:D

The serialized file is about 2.3GB, but the unserialized map is about 6.2GB. So it seems that the overhead is higher than sparse_hash_map.

My code is here:

int main(int argc, char** argv)
{
	size_t nNum = 1e8;
	cout << "testing size:\t" << nNum << endl;

	//dense_hash_map<uint64_t, string> mUniq;
	//mUniq.set_empty_key(0);
	spp::sparse_hash_map<uint64_t, string> mUniq;
	//unordered_map<uint64_t, string> mUniq;

	// insert
	auto t1 = TClock::now();
	size_t nInsert = 0;
	for (size_t i = 0; i < nNum; ++i)
	{
		mUniq[ULLONG_MAX-i] = to_string(i);
		++nInsert;
	}
	cout << "insert done:\t" << duration_cast<seconds>(TClock::now()-t1).count() << endl;

	FILE *out = fopen("data/uniq1.map", "wb");
	mUniq.serialize(FileSerializer(), out);
	fclose(out);
	mUniq.clear();
	cout << "clean:\t" << mUniq.size() << endl;

	// look up
	FILE *input = fopen("data/uniq1.map", "rb");
	mUniq.unserialize(FileSerializer(), input);
	fclose(input);

	t1 = TClock::now();
	size_t nMatch = 0;
	for (size_t i = 0; i < nNum; ++i)
	{
		if (mUniq[ULLONG_MAX-i] == to_string(i)) ++nMatch;
	}
	cout << "look-up done:\t" << duration_cast<seconds>(TClock::now()-t1).count() << endl;

	cout << mUniq.size() << endl;
	cout << nMatch << endl;
	//cout << nInsert << endl;

	return 0;
}

**Comment by greg7mdp** [comment]
I think I have the answer, but please tell me what compiler, platform and standard library you are using.

**Comment by zhaoyanswill** [comment]
My os is Ubuntu 14.04. g++ version is 4.9.3. Thanks!

**Comment by greg7mdp** [comment]
Hum, I think for g++4.9 with GNU libstdc++, each string occupies 8 bytes (for the pointer) + 25 bytes + the capacity in the heap.

For your numbers (average length 8 characters), the size in the file would be 16 characters, but the size in memory for the std::string would be 8 + 25 + 9 so at least 42 bytes, which is over 2.5 times the memory for serialization.

I would suggest that you try using something this as your sparse_hash_map type:

```
typedef struct SmallStr 
{
    SmallStr(size_t i) { sprintf(_str, "%lld", i); }
    char& operator[](int i) { return _str[i]; }
    char _str[10];
} SmallStr;

spp::sparse_hash_map<uint64_t, SmallStr> mUniq;

for (size_t i = 0; i < nNum; ++i)
    mUniq[ULLONG_MAX-i] = SmallStr(i);
```

**Comment by zhaoyanswill** [comment]
I see. Lesson learned! Those strings are not unique. I’ll put them in vector and then just put their index in the map. Thank you!

**Comment by greg7mdp** [comment]
Perfect, glad I was able to help, I'll close the issue.
