### ISSUE TITLE
Error when compile: is not a special member function which can be defaulted

### ISSUE THREAD

**Issue by lengocthuong15** [greg7mdp/sparsepp#91]
Hi,
When I included the file spp.h into my project and compile it, it hit the error message as below
spp.h(3722) : error C2610: 'spp::sparse_hash_map<Key,T,HashFcn,EqualKey,Alloc> &spp::sparse_hash_map<Key,T,HashFcn,EqualKey,Alloc>::operator =(spp::sparse_hash_map<Key,T,HashFcn,EqualKey,Alloc> &&)' : is not a special member function which can be defaulted

**Comment by greg7mdp** [comment]
@lengocthuong15 - Issue is fixed. Thanks for reporting it! Please let me know if you still have a problem.

**Comment by lengocthuong15** [comment]
The issue has been fixed, thank you.
